== References

The following normative documents contain provisions that, through reference in this text, constitute provisions of this document. For dated references, subsequent amendments to, or revisions of, any of these publications do not apply. For undated references, the latest edition of the normative document referred to applies.

ISO: ISO 12639, TIFF™ Revision 6.0 Final, June 3, 1992 Adobe® Systems Incorporated, 2004

[[New_WKT_Reference]]ISO / OGC: ISO 19162:2015 _Geographic information -- Well-known text representation of coordinate reference systems_. Also OGC 12-063r5. http://docs.opengeospatial.org/is/12-063r5/12-063r5.html, 2015

[[Old_WKT_Reference]]OGC: OGC 01-009 _Implementation Specification: Coordinate Transformation Services Revision 1.0_ http://portal.opengeospatial.org/files/?artifact_id=999[_http://portal.opengeospatial.org/files/?artifact_id=999_], 2001

OGC: GC 08-015r2, _Abstract Specification Topic 2 – Spatial Referencing by Coordinates_, (ISO 19111), 2010

OGC: OGC 07-011, _Abstract Specification Topic 6: Schema for coverage geometry and functions_, (ISO 19123), 2006

OGC: OGC 15-115r3 _CDB Core Standard: Model and Physical Data Store Structure_ https://portal.opengeospatial.org/files/?artifact_id=72712, 2016

OGC: OGC 09-146r6 _Coverage Implementation Schema 1.1_ http://docs.opengeospatial.org/is/09-146r6/09-146r6.html, 2017

OGC: OGC 12-128r12, _GeoPackage Encoding Standard 1.1_ http://www.geopackage.org/spec110/, 2015

OGC: OGC 06-121r9 Web Services Common Standard, version 2.0.0, 2010

[[_Ref425705852]]OGC: OGC 08-094r1, OGC^®^ SWE Common Data Model Encoding Standard, version 2.0, 2011

UCUM : http://unitsofmeasure.org/ucum.html[The Unified Code for Units of Measure]. 2014

Adobe Systems Incorporated: Adobe _TIFF ™ Revision 6.0 Final_, ftp://download.osgeo.org/libtiff/doc/TIFF6.pdf[_ftp://download.osgeo.org/libtiff/doc/TIFF6.pdf_], 1992
