language: ruby
rvm:
- 2.0.0
branches:
  only:
  - master
script: rake travis
env:
  global:
    secure: e4sRZ8Bqx703zfHZSTCAX/xZ015FCcXy0Xl/QpS/3YpdvUNs2VDWsvJMv8nDMZD/A0rhVfmnTT4lG3eo7QLuunwnNCV/JYhXjF05ajE+TMY4fe6WHWuQEVL0L5AlA9EpPsQRwkZIRDPTa+RJ4y0lebA1j6aFUZL+BRS7VywiPmw=
