== References
The following normative documents contain provisions that, through reference in this text, constitute provisions of this document. For dated references, subsequent amendments to, or revisions of, any of these publications do not apply. For undated references, the latest edition of the normative document referred to applies.

[[OGC-06-103r4]]
OGC: OGC 06-103r4, OpenGIS Implementation Standard for Geographic Information - Simple feature access - Part 1: Common architecture (2011) https://portal.ogc.org/files/?artifact_id=25355

[[OGC-12-128r17]]
OGC: OGC 12-128r17, OGC GeoPackage Encoding Standard 1.3.0 (2020) http://www.geopackage.org/spec130/index.html

[[OGC-17-066r1]]
OGC: OGC 17-066, OGC GeoPackage Extension for Tiled Gridded Coverage Data (2017) http://docs.opengeospatial.org/is/17-066r1/17-066r1.html

[[OGC-17-083r2]]
OGC: OGC 17-083r2, OGC Two Dimensional Tile Matrix Set (2019) http://docs.opengeospatial.org/is/17-083r2/17-083r2.html

[[OGC-18-000]]
OGC: OGC 18-000, OGC GeoPackage Related Tables Extension (2019) http://docs.opengeospatial.org/is/18-000/18-000.html

[[OGC-18-010r7]]
OGC: OGC 18-010r7, Geographic information — Well-known text representation of coordinate reference systems (2019) https://docs.opengeospatial.org/is/18-010r7/18-010r7.html (also ISO 19162:2019)

