== Terms and Definitions
This document used the terms defined in https://portal.ogc.org/public_ogc/directives/directives.php[OGC Policy Directive 49], which is based on the ISO/IEC Directives, Part 2, Rules for the structure and drafting of International Standards. In particular, the word “shall” (not “must”) is the verb form used to indicate a requirement to be strictly followed to conform to this standard and OGC documents do not use the equivalent phrases in the ISO/IEC Directives, Part 2.

This document also uses terms defined in the OGC Standard for Modular specifications (https://portal.opengeospatial.org/files/?artifact_id=34762[OGC 08-131r3]), also known as the 'ModSpec'. The definitions of terms such as standard, specification, requirement, and conformance test are provided in the ModSpec.

For the purposes of this document, the following additional terms and definitions apply.

Conceptual Model::
model that defines concepts of a universe of discourse [ISO 19101-1:2014, 4.1.5]

GeoPackage Encoding Standard::
   The original encoding standard for GeoPackage adopted by OGC as 12-128. **GES** for short.

GeoPackage SQLite Configuration::
    consists of the SQLite 3 software library and a set of compile- and runtime configurations options.

GES::
    GeoPackage Encoding Standard (see above).

Implementation Specification::
    Specified on the OGC Document Types Register at http://www.opengis.net/def/doc-type/is

Logical Model::
    An abstracted representation of domain knowledge that could feasibly be used in Model Driven Architecture to generate physical artifacts. (source?)

Platform Independent Model::
    a model that is independent of a specific platform
    [Object Management Group, Model Driven Architecture Guide rev. 2.0]

Platform Specific Model::
    a model of a system that is defined in terms of a specific platform [Object Management Group, Model Driven Architecture Guide rev. 2.0]

