== Conformance
This standard defines a Conceptual Model which is independent of any encoding or formatting techniques.
The Standardization Targets for this standard are:

. Conceptual Models (extended versions of this conceptual model)
. Implementation Specifications (encodings of this conceptual model)

=== Conceptual Models
A Conceptual Model standardization target is a version of the GeoPackage Conceptual Model (CM) tailored for a specific user community.
This tailoring can include:

. Omission of one or more of the optional UML packages
. Reduction of the multiplicity for an attribute or association
. Restriction on the valid values for an attribute
. Additional concepts documented through ADEs.

Of these options, actions #1, #2, and #3 can be performed when creating an implementation specification.
Only action #4 requires an extension of the CM.
These extensions are accomplished using the extension mechanism described in ...
Extensions of the CM conform with the Extension Conformance Class.

=== Implementation Specifications
Implementation Specifications define how a Conceptual Model should be implemented using a specific technology.
Conformant Implementation Specifications provide evidence that they are an accurate representation of the Conceptual Model.
This evidence should include implementations of the abstract tests specified in Annex A (normative) of this document.
Since this standard is agnostic to the implementing technologies, the specific techniques to be used for conformance testing cannot be specified.
Implementation Specifications need to provide evidence of conformance which is appropriate for the implementing technologies.
This evidence should be provided as an annex to the Implementation Specification document.

=== Conformance Classes
This standard identifies seventeen (17) conformance classes.
One conformance class is defined for each package in the UML model.
Each conformance class is defined by one requirements class.
The tests in Annex A are organized by Requirements Class.
So an implementation of the Core conformance class must pass all tests specified in Annex A for the Core requirements class.

Of these seventeen conformance classes, only the Core conformance class is mandatory.
All other conformance classes are optional.
In the case where a conformance class has a dependency on another conformance class, that conformance class should also be implemented.
The CM is defined by a UML model.
This standard is a representation of that UML model in document form.
In the case of a discrepancy between the UML model and this document, the UML model takes precedence.
