== Scope
This OGC document describes an OGC Conceptual Model (CM) and Logical Model (LM) Standard for encoding geospatial information based on the GeoPackage Standard.
A *GeoPackage* is an open, standards-based, platform-independent, portable, self-describing, compact format for transferring geospatial information.
The GeoPackage Conceptual Model Standard (this document) describes the model for encoding the following:

* Vector features;

* Tile matrix sets of imagery and raster maps at various scales;

* Attributes (non-spatial data); and

* Extensions.

The CM and LM are Platform Independent Models (PIMs).
The CM is a high level description of the concepts involved in the GeoPackage standard.
The LM is an abstract representation of an interface or data model that can be _executed_ to produce physical artifacts.
As such, neither the GeoPackage CM nor the LM can be implemented directly.
Rather, they serve as the base for Platform Specific Models (PSM).
A PSM adds to the PIM the technology-specific details needed to fully define the model for use with a specific technology.
The PSM can then be used to generate artifacts such as schemas needed to build GeoPackage implementations.
These artifacts include table definitions, integrity assertions, format limitations, and content constraints.

This document was developed retroactively from the GeoPackage Encoding Standard (GES) 1.3.0.
At the time the GES was first developed, OGC members decided that developing the CM or LM was not necessary as the GES was intended specifically for the SQLite database format. 
However, as SQLite's inherent limitations became more apparent, stakeholders determined that it would be beneficial to the community to document and standardize the CM and LM so that other PSMs could potentially be supported in the future.
As a result, this document is agnostic to potential uses and implementation technologies.
The OGC believes that GeoPackage has the potential to evolve to support use cases and computing environments that go beyond what was originally conceived for the GES.
