
.Preface

The GeoPackage conceptual and logical models were developed in response to numerous requests from the GeoPackage implementation and developer community.

Attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights. The Open Geospatial Consortium shall not be held responsible for identifying any or all such patent rights.

Recipients of this document are requested to submit, with their comments, notification of any relevant patent claims or other intellectual property rights of which they may be aware that might be infringed by any implementation of the standard set forth in this document, and to provide supporting documentation.

[abstract]
== Abstract

This document presents the conceptual and logical models for version 1.x of the https://www.ogc.org/pressroom/pressreleases/4416[OGC GeoPackage Standard].
The intent is that these models can be used to implement the GeoPackage standard using technology other than a SQLite database.

[.preface]
== Submitters

All questions regarding this submission should be directed to the editor or the submitters:

[%unnumbered]
|===
h| Name h| Affiliation
|Jeff Yutzler |Image Matters LLC
|Amy Youmans  |US Army Geospatial Center
|Carl Reed    |Carl Reed and Associates
|===

[.preface]
== Introduction

This OGC document describes an OGC Conceptual Model (CM) and Logical Model (LM) Standard for encoding geospatial information based on the GeoPackage Standard.
A *GeoPackage* is an open, standards-based, platform-independent, portable, self-describing, compact format for transferring geospatial information.

This document was developed retroactively from the GeoPackage Encoding Standard (GES) 1.3.0.
At the time the GES was first developed, OGC members decided that developing the CM or LM was not necessary as the GES was intended specifically for the SQLite database format. 
However, as SQLite's inherent limitations became more apparent, stakeholders determined that it would be beneficial to the community to document and standardize the CM and LM so that other PSMs could potentially be supported in the future.
As a result, this document is agnostic to potential uses and implementation technologies.
The OGC believes that GeoPackage has the potential to evolve to support use cases and computing environments that go beyond what was originally conceived for the GES.
