== GeoPackage Conceptual Model (Normative)
This section presents the normative definition of the GeoPackage Conceptual Model (CM).
The CM consists of a set of terms and their definitions.
_Since most readers will be familiar with the GES, an indication of how GeoPackage concepts are realized in the GES is presented in italics._

=== Core
All GeoPackages conform to Core.

Attribute::
  A characteristic of an entity. (SOURCE: Adapted from ISO 19101-1:2014)
  _In the GES, an attribute is realized through a column value of a user-defined table._

Attribute Type::
  a characteristic of an entity type.
  An attribute type has a name, a data type, and a value domain associated to it.
  No restrictions are implied as to the type of attributes a user-defined type may have.
  Not all entity types have attributes. (SOURCE: Adapted from ISO 19101-1:2004)
  _In the GES, an attribute is realized through a column of a user-defined table._

Coordinate Reference System (CRS)::
A coordinate reference system, or spatial reference system, is a set of mathematical rules for specifying how coordinates are to be assigned to points that is related to an object by a datum. (SOURCE: ISO 19111:2019)
_The GES uses the term "spatial reference system." In the GES, a spatial reference system is realized through a `gpkg_spatial_ref_sys` row._
  
Entity::
  An individual item that is perceivable or conceivable. (SOURCE: ISO/IEC 21838-1:2021)
  _In the GES, an entity is realized through a row of a user-defined table._

  
[NOTE]
====
In this standard, "entity" is used to denote the concept that is denoted "particular" in ISO/IEC 21838-1:2021).
For the purposes of this standard, an entity is simply a unit of content contained in a GeoPackage.
This is deliberately open-ended so as not to prejudice the content that a GeoPackage may contain.
====

Entity Store::
  a container for entities.
  _In the GES, an entity store is realized through a user-defined table and a row in `gpkg_contents`._

Entity Type::
  A class of entities having common characteristics. (SOURCE: Adapted from 19156:2011)
  _In the GES, an entity type is realized through the schema of a user-defined table._
  
GeoPackage::
  an open, standards-based, platform-independent, portable, self-describing, compact format for transferring geospatial information.
  _In the GES, a GeoPackage is realized through a GeoPackage file._

Spatial Reference System (SRS)::
  see "Coordinate Reference System".

=== Features

GeoPackages that conform to the Features Requirements Class contain the content represented here.
The Features Requirements Class implements Simple Features as per OGC 06-103r4.
The definitions of the concepts below are from that document unless otherwise indicated.

Feature::
  An abstraction of real world phenomena. (SOURCE: ISO 19101).
  For the purposes of this document, it refers to an individual realization thereof.
  Features can be classified as _geographic_ and _non-geographic_.
  _In the GES, the Features Requirements Class is for geographic features._
  _For non-geographic features, see <<Attributes>> below._

Feature Store::
   A container for features.
  _In the GES, a feature store is realized through a user-defined features table (for geographic features) or attributes table (for non-geographic features; see below)._

Feature Type::
  A class of features having common characteristics. (SOURCE: Adapted from ISO 19101)
  _In the GES, a feature type is realized through the schema of a user-defined features table (for geographic features) or attributes table (for non-geographic features; see below)._

Geographic Feature::
  A representation of real world phenomenon associatied with a location relative to the Earth. (SOURCE: ISO 19125-2:2004)
  _In the GES, a geographic feature is realized through a row of a user-defined features table._

Geometry::
  A spatial object representing a geometric set. (SOURCE: ISO 19107)
  _In the GES, a geometry is realized through a Well Known Binary value for a geometry attribute for a feature in a user-defined features table._

Geometry Attribute::
   A specialization of _attribute_ for geometry values.
   _In the GES, a geometry attribute is realized through a column of a user-defined features table._

Geometry Attribute Type::
   a specialization of attribute types for a geometry data type.
   _In the GES, a geometry attribute type is realized through a row of `gpkg_geometry_columns`._

=== Tiles

GeoPackages that conform to the Tiles Requirements Class contain the content represented here.
The Tiles Requirements Class implements Tile Matrix Sets as per OGC 17-083r2.
The definitions of the concepts below are from that document unless otherwise indicated.

Tile::
  a geometric shape with known properties that may or may not be the result of a tiling (tessellation) process.
  A tile consists of a single connected "piece" (topological disc) without "holes" or "lines".
  In this CM, a tile is restricted to a small rectangular representation of geographic data, often part of a set of such elements, covering a tiling scheme and sharing similar information content and graphical styling.
  A tile can be uniquely defined in a tile matrix by one integer index in each dimension. 
  Tiles are mainly used for fast transfer (particularly in the web) and easy display at the resolution of a rendering device.
  Tiles can be grid based pictorial representations, coverage subsets, or feature based representations (e.g., vector tiles).
  _In the GES, a tile is realized through a row of a user-defined tiles table._

Tile Matrix::
  a grid tiling scheme that defines how space is partitioned into a set of conterminous tiles at a fixed scale.
  _In the GES, a tile matrix is realized through a row of `gpkg_tile_matrix`._

[NOTE]
====
A tile matrix constitutes a tessellation of the space that resembles a matrix in a 2D space characterized by a matrix width (columns) and a matrix height (rows).
====

Tile Matrix Set::
  a tiling scheme composed by collection of tile matrices defined at different scales covering approximately the same area and has a common coordinate reference system.
  _In the GES, a tile matrix set is realized through a row of `gpkg_tile_matrix_set`._

Tile Pyramid::
  a tile set organized in pyramid structure of tiles of different spatial extent and resolution at different zoom levels.
  _In the GES, a tile pyramid is realized through a user-defined tiles table and a row of `gpkg_contents`._
  
Tile Set::
  a set of tiles – a collection of subsets of the space being partitioned [OGC 19-014r3].
  In this standard, In this CM, a tile set is a series of actual tiles containing data and following a common tiling scheme.

Tiling Scheme::
  a scheme that defines how space is partitioned into individual tiled units.
  A tiling scheme defines the spatial reference system, the geometric properties of a tile, which space a uniquely identified tile occupies, and reversely, which unique identifier corresponds to a space satisfying the geometric properties to be a tile. [OGC 19-014r3]

[NOTE]
====
A tiling scheme is not restricted to a coordinate reference system or a tile matrix set and allows for other spatial reference systems such as DGGS and other organizations including irregular ones.
====

[[attributes]]
=== Attributes

GeoPackages that conform to the Attributes Requirements Class contain the content represented in <<Attributes_Classes>>.

[NOTE]
====
OGC 12-128 defined this concept as "attributes".
However, this conflicts with the standard definition of an attribute as a member of a class.
====

Attributes Store::
   a container for attributes sets.
   _In the GES, an attributes store is realized through a user-defined attributes table._  

Non-Geographic Feature Set::
   a user-defined type with one or attributes, none of which is a geometry.
   _In the GES, a non-geographic feature set is realized through the schema of a user-defined attributes table._

Non-Geograpic Feature Set Type::
   A class of features having common characteristics. (SOURCE: Adapted from ISO 19101)
   _In the GES, an non-geographic feature set type is realized through the schema of a user-defined attributes table._

[[extensions]]
=== Extensions

GeoPackages that conform to the Extensions Requirements Class contain the content represented here.

Extension::
  a set of one or more requirements clauses that either profiles / extends existing requirements clauses in the GeoPackage standard or adds new requirements clauses.
  _In the GES, extensions are realized through rows of `gpkg_extensions`._
  
=== Metadata

GeoPackages that conform to the Metadata Requirements Class contain the content represented here.

Metadata::
  for the purposes of this document, a discrete unit of data about data. (SOURCE: ISO 19115-1)
  _In the GES, metadata is realized through rows of `gpkg_metadata`._
  
Metadata Reference::
  a reference indicating the element(s) that particular metadata pertains to.
  _In the GES, a metadata reference is realized through a row of `gpkg_metadata_reference`._

=== Schema

GeoPackages that conform to the Schema Requirements Class contain the content represented here.

Attribute Descriptor::
  an extended description of an attribute type.
  _In the GES, an attribute descriptor is realized through a row of `gpkg_data_columns`._
  
Constraint::
  a restriction on the range of an attribute value.
  _In the GES, a constraint is realized through a row of `gpkg_data_column_constraints`._

=== Tiled Gridded Coverages

GeoPackages that conform to the Tiled Gridded Coverage Requirements Class contain the content represented in here.

Coverage::
  a function that describe characteristics of real-world phenomena that vary over space and/or time.
  Typical examples are temperature, elevation and precipitation.
  A coverage is typically represented as a data structure containing a set of such values, each associated with one of the elements in a spatial, temporal or spatiotemporal domain.
  Typical spatial domains are point sets (e.g. sensor locations), curve sets (e.g. contour lines), grids (e.g. orthoimages, elevation models), etc.
  A property whose value varies as a function of time may be represented as a temporal coverage or time-series [SOURCE: ISO-19109].

Coverage Tile::
  a tile containing coverage data.
  _In the GES, a coverage tile is realized through a row in a user-defined tiles table and a row in `gpkg_2d_gridded_tile_ancillary`._

Tiled Gridded Coverage::
  a tile pyramid containing coverage data encoded as coverage tiles.
  _In the GES, a tiled gridded coverage is realized through a user-defined tiles table, a row in `gpkg_2d_gridded_coverage_ancillary`, and a row in `gpkg_contents`._

=== Related Tables

GeoPackages that conform to the Related Tables Requirements Class contain the content represented here.
The purpose of this requirements class is to support a many-to-many relationship between two entities, defined as the "base" entity and the "related" entity.
In the CM there is no semantic difference between these concepts, but profiles may be used to provide those semantics.

Extended Relation::
  a descriptor for the relationship between the base entity and the related entity.
  _In the GES, an extended relation is realized through a row in `gpkgext_relations`._

