== Verification and Validation

### Executable Test Suite (ETS)
This is software that allows the user to load a GeoPackage and receive a report on any standard compliance issues. It is currently built on top of the OGC TEAM Engine.

#### Adoption
Currently the ETS is in beta. We would like it to become official so that we can maintain proper lists of compliant software implementations.
* [x] GitHub
* [x] [Beta Site](http://cite.opengeospatial.org/te2/about/gpkg12/1.2/site/)
* [ ] Three implementations
  * [x] Esri
  * [x] NGA/BITS
  * [ ] ???
* [ ] OGC approval

#### Maintenance
* [x] [Open tickets](https://github.com/opengeospatial/ets-gpkg12/issues)
* [ ] Better reporting
  * [ ] Clearer output report
  * [ ] Version of file
  * [ ] Warnings
* [x] Integration with Simple Features test
* Acquire additional samples (ongoing)

### Interoperability Suite
This is software that allows the user to load a GeoPackage. It will report both standard compliance issues and interoperability issues that fall outside of what can be governed by the standard. We do not currently have an advocate for this activity.

### Implementations list
OGC maintains a list of [registered implementations](http://www.opengeospatial.org/resource/products/compliant). These can be self-selected, but organizations who have gone through the full certification process are identified appropriately.

### Interoperability Tests
This section describes activities where representatives of software development teams get together and attempt to prove the interoperability of their software with files produced by other groups.

#### [Geospatial to the Edge Plugfest](http://www.opengeospatial.org/projects/initiatives/geoedgeplugfest)
This activity is focused primarily on National System for GEOINT (NSG) profiles but it also addresses some infrequently explored parts of the standard.
