[[attributes]]
=== Attributes

==== Introduction

Non-spatial attribute data are sets (or tuples or rows) of observations that may not have an explicit geometry property. In GeoPackage, this data is stored in user-defined attribute tables. These tables may contain properties such as an ID or geo-locatable address that allow them to be relationally linkable to rows in other attribute, feature or tile tables.

Examples of attribute data include:

* meteorological readings from a weather station
* flow readings from a stream gauge
* traffic volumes from embedded highway sensors
* lists of customers
* delivery stops
* work orders

==== Contents
===== Data
====== Contents Table - Attributes Row
[[r118]]
[caption=""]
.Requirement 118
====
The `gpkg_contents` table SHALL contain a row with a `data_type` column value of "attributes" for each attributes data table or view.
====

[[attributes_user_tables]]
==== Attributes User Data Tables

===== Data

[[attributes_table_definition]]
====== Table Definition

Non-spatial attribute data is stored in user-defined Attribute tables. Attribute sets are rows in an Attribute table. The attributes are columns in a Attribute table. (A GeoPackage is not required to contain any Attribute data tables. Attribute data tables in a GeoPackage may be empty.)

[[r119]]
[caption=""]
.Requirement 119
====
A GeoPackage MAY contain tables or views containing attribute sets. Every such Attribute table or view in a GeoPackage SHALL be structured consistently with <<gpkg_attributes_example>> and <<example_attributes_table_sql>>.
====

[[r151]]
[caption=""]
.Requirement 151
====
An attributes table or view SHALL have a column that uniquely identifies the row. For a feature table, the column SHOULD be a primary key. If there is no primary key column, the first column SHALL be of type INTEGER and SHALL contain unique values for each row.
====

[NOTE]
=====
Using an integer primary key in an attributes table allows attributes to be linked to row level metadata records in the `gpkg_metadata` table by rowid <<B5>> values in the `gpkg_metadata_reference` table as described in clause <<_metadata_reference_table>> below. Since the concept of primary keys does not exist for views in SQLite, this requirement also provides a way to produce a compliant attributes view with a discoverable key-like column^<<K17>>^.
=====

[#gpkg_attributes_example,reftext='{table-caption} {counter:table-num}']
.GeoPackage Attributes Example Table or View Definition
[cols=",,,,",options="header",]
|=======================================================================
|Column Name |Col Type |Column Description |Null |Key
|`id` |INTEGER |Primary key |no |PK
|`text_attribute` |TEXT |Text attribute of feature |yes |
|`real_attribute` |REAL |Real attribute of feature |yes | 
|`boolean_attribute` |BOOLEAN |Boolean attribute of feature |yes |
|`raster_or_photo` |BLOB |Photo of the area |yes |
|=======================================================================

