== Registered Extensions

This clause specifies requirements for GeoPackage extensions.
Definitions of those extensions in the form specified by the template in <<extension_template>> are provided in referenced Annexes.
 
=== Features

==== Geometry Types

===== Data

The optional extension capabilities defined in sub clauses and requirement statements of this clause and in <<extension_geometry_types>> MAY be implemented by any GeoPackage that implements the requirements of clause <<features>> and clause 2.6.1.1 on which they depend, as specified in <<abstract_test_suite>>.

===== Extension Types

[requirement]
A GeoPackage MAY store feature table geometries with the extended non-linear geometry types (CircularString, CompoundCurve, CurvePolygon, MultiCurve, MultiSurface, Curve, Surface) in <<geometry_types>>.
If it does so, they SHALL be encoded in the GeoPackageBinary geometry format.

===== Extensions Types - Extensions Name

[requirement]
An extension name to specify a feature geometry extension type SHALL be defined for the “gpkg” author name using the “gpkg_geom_<gname>” template where <gname> is the uppercase name of the extension geometry type from <<geometry_types>> used in a GeoPackage.

===== Extensions Types - Extensions Row

[requirement]
A GeoPackage that contains a gpkg_geometry_columns table or updateable view with row records that specify extension geometry_type_name column values SHALL contain a gpkg_extensions table that contains row records with table_name and column_name values from the gpkg_geometry_columns row records that identify extension type uses, and extension_name column values for each of those geometry types constructed per clause 3.1.1.1.2.

==== Geometry Encoding

===== Data

The optional registered extension capabilities defined in sub clauses and requirement statements of this clause and <<extension_geometry_encoding>> MAY be implemented by any GeoPackage that implements requirements of clause <<features>> and clause 2.6 on which they depend.

===== Extensions Encoding

[requirement]
The ExtendedGeoPackageBinary format defined in <<extension_geometry_encoding>> SHALL be used to encode geometry types other than those specified in clauses 2.1.4 and 3.1.1 and listed in <<geometry_types>>.

===== Extensions Encoding - Extensions Name

[requirement]
An extension name to specify a feature geometry extension type encoded in the ExtendedGeoPackageBinary format SHALL be defined for an author name that is NOT “gpkg” using the “<author_name>_geom_<gname> template where <gname> is the uppercase name of an extension geometry type NOT listed in <<geometry_types>> used in a GeoPackage.

===== Extensions Encoding - Extensions Row

[requirement]
An Extended GeoPackage that contains a gpkg_geometry_columns table or updateable view with row records that specify extension geometry_type_name column values other than those specified in clauses 2.1.4 and 3.1.1 and listed in <<geometry_types>> SHALL contain a gpkg_extensions table that contains row records with table_name and column_name values from the gpkg_geometry_columns row records that identify extension type uses, and extension_name column values for each of those geometry type constructed per clause 3.1.2.1.2.

==== Spatial Indexes

===== Data

The optional registered extension capabilities defined in sub clauses and requirement statements of this clause and <<extension_rtree>> MAY be implemented by any GeoPackage that implements requirements of clause <<features>> and clause 2.6 on which they depend.

===== Spatial Indexes Implementation
Spatial indexes provide a significant performance advantage for searches with basic envelope spatial criteria that return subsets of the rows in a feature table with a non-trivial number (thousands or more) of rows.  

[requirement]
A GeoPackage SHALL implement spatial indexes on feature table geometry columns as specified in clause 3.1.3.1.1 using the SQLite Virtual Table RTrees and triggers specified in <<extension_rtree>>.

===== Spatial Indexes - Extensions Name

[requirement]
The “gpkg_rtree_index” extension name SHALL be used as a gpkg_extensions table extension name column value to specify implementation of spatial indexes on a geometry column.

===== Spatial Indexes - Extensions Row

[requirement]
A GeoPackage that implements spatial indexes SHALL have a gpkg_extensions table that contains a row for each spatially indexed column with extension_name “gpkg_rtree_index”, the table_name of the table with a spatially indexed column, and the column_name of the spatially indexed column.

==== Geometry Type Triggers

===== Data
The optional extension capabilities defined in sub clauses and requirement statements of this clause MAY be implemented by any GeoPackage that implements requirements of clause <<features>> and clause 2.6 on which they depend.

===== Geometry Type Triggers – Implementation

[requirement]
A GeoPackage SHALL include the SQL insert and update triggers specified in <<extension_geometry_type_triggers>> on every geometry column to enforce the geometry type values specified for those columns in the gpkg_geometry_columns table.

===== Geometry Type Triggers – Extensions Name

[requirement]
The “gpkg_geometry_type_trigger” extension name SHALL be used as a gpkg_extensions table extension name column value to specify implementation of geometry type triggers.
===== Geometry Type Triggers – Extensions Row

[requirement]
A GeoPackage that implements geometry type triggers on geometry columns SHALL contain a gpkg_extensions table that contains a row for each such geometry column with extension_name “gpkg_geometry_type_trigger”, table_name of the feature table with a geometry column, and column_name of the geometry column.

==== SRS_ID Triggers

===== Data

The optional extension capabilities defined in sub clauses and requirement statements of this clause MAY be implemented by any GeoPackage that implements requirements of clause <<features>> and clause 2.6 on which they depend.

===== SRS_ID Triggers – Implementation

[requirement]
A GeoPackage SHALL include the SQL insert and update triggers specified in <<extension_geometry_srsid_triggers>> on every geometry column to enforce the srs_id values specified for those columns in the gpkg_geometry_columns table.

===== SRS_ID Triggers – Extensions Name

[requirement]
The “gpkg_srs_id_trigger” extension name SHALL be used as a gpkg_extensions table extension name column value to specify implementation of SRS_ID triggers specified in <<extension_geometry_srsid_triggers>>.

===== SRS_ID Triggers – Extensions Row

[requirement]
A GeoPackage that implements srs_id triggers on feature table geometry columns SHALL contain a gpkg_extensions table that contains a row for each geometry column with extension_name “gpkg_srs_id_trigger”, table_name of the feature table with a geometry column, and column_name of the geometry column.

=== Tiles

==== Zoom Levels

===== Data

The optional extension capabilities defined in sub clauses and requirement statements of this clause MAY be implemented by any GeoPackage that implements the requirements of clause <<tiles>> and clause 2.6.1.1 on which they depend.

===== Zoom Other Intervals

As a registered extension, a GeoPackage MAY contain tile pyramid user data tables with pixel sizes that vary by irregular intervals or by regular intervals other than a factor of two (the default) between adjacent zoom levels, as described in clause 2.2.3 and the gpkg_tile_matrix table in clause 2.2.6 Table 9.

===== Zoom Other – Extensions Name

[requirement]
The “gpkg_zoom_other” extension name SHALL be used as a gpkg_extensions table extension name column value to specify implementation of other zoom intervals on a tile pyramid user data table as specified in <<extension_zoom_other_intervals>>.

===== Zoom Other – Extensions Row

[requirement]
A GeoPackage that implements other zoom intervals SHALL have a gpkg_extensions table that contains a row for each tile pyramid user data table with other zoom intervals with extension_name “gpkg_zoom_other”, the table_name of the table with other zoom intervals, and the “tile_data” column_name.

[[tile_enc_webp]]
==== Tile Encoding WEBP

===== Data

The optional extension capabilities defined in sub clauses and requirement statements of this clause MAY be implemented by any GeoPackage that implements the requirements of clause <<tiles>> and clause 2.6.1.1 on which they depend.

===== WEBP MIME Type

As a registered extension, a GeoPackage that contains a tile pyramid user data table that contains tile data MAY store tile_data in MIME type image/x-webp[26].

===== WEBP -- Extensions Name

[requirement]
The “gpkg_webp” extension name SHALL be used as a gpkg_extensions table extension name column value to specify storage of tile pyramidimages in WEBP format as specified in <<extension_tiles_webp>>.

===== WEBP -- Extensions Row

[requirement]
A GeoPackage that contains tile pyramid user data tables with tile_data columns that contain images in WEBP format SHALL contain a gpkg_extensions table that contains row records with table_name values for each such table, “tile_data” column_name values and extension_name column values of “gpkg_webp”.

[[tile_enc_tiff]]
==== Tiles Encoding TIFF

===== Data

The optional extension capabilities defined in sub clauses and requirement statements of this clause MAY be implemented by any GeoPackage that implements the requirements of clause <<tiles>> and clause 2.6.1.1 on which they depend.

===== TIFF MIME Type

As a registered extension, a GeoPackage that contains a tile pyramid user data table that contains tile data MAY store tile_data in MIME type image/tiff [27] for GeoTIFF images [28] that meet the requirements of the NGA Implementation Profile [29] for coordinate transformation case 3 where the position and scale of the data is known exactly, and no rotation of the image is required.

===== TIFF -- Extensions Name

[requirement]
The “gpkg_tiff” extension name SHALL be used as a gpkg_extensions table extension name column value to specify storage of raster images in TIFF format as specified in <<extension_tiles_tiff>>.

===== Extensions Row

[requirement]
A GeoPackage that contains tile matrix user data tables with tile_data columns that contain raster images in TIFF format per <<extension_tiles_tiff>> SHALL contain a gpkg_extensions table that contains row records with table_name values for each such table, “tile_data” column_name values and extension_name column values of “gpkg_tiff”.

[[tile_enc_nitf]]
==== Tile Encoding NITF

===== Data

The optional extension capabilities defined in sub clauses and requirement statements of this clause MAY be implemented by any GeoPackage that implements the requirements of clause <<tiles>> and clause 2.6.1.1 on which they depend.

===== NITF MIME Type

As a registered extension, a GeoPackage that contains a tile matrix user data table that contains tile data MAY store tile_data in MIME type application/vnd.NITF[46] for National Imagery Transmission Format images.

===== NITF -- Extensions Name

[requirement]
The “gpkg_nitf” extension name SHALL be used as a gpkg_extensions table extension name column value to specify storage of raster images in NITF format as specified in <<extension_tiles_nitf>>.

===== NITF -- Extensions Row

[requirement]
A GeoPackage that contains tile matrix user data tables with tile_data columns that contain raster images in NITF format SHALL contain a gpkg_extensions table that contains row records with table_name values for each such table, “tile_data” column_name values and extension_name column values of “gpkg_nitf”.
