=== Metadata

The optional capabilities defined in sub clauses and requirement statements of this clause MAY be implemented by any
*GeoPackage file*.

==== Introduction

Two tables in a GeoPackage file provide a means of storing metadata in MIME <<N25>> encodings that are defined in
accordance with any authoritative metadata specifications, and relating it to the features, rasters, and tiles data in a
GeoPackage. These tables are intended to provide the support necessary to implement the hierarchical metadata model
defined in ISO 19115 <<N40>>, Annex B B.5.25 MD_ScopeCode, Annex I and Annex J, so that as GeoPackage data is captured and
updated, the most local and specific detailed metadata changes associated with the new or modified data MAY be captured
separately, and referenced to existing global and general metadata.

The `gpkg_metadata` table that contains metadata is described in clause <<_metadata_table>>, and the
`gpkg_metadata_reference` table that relates `gpkg_metadata` to GeoPackage data is described in clause
<<_metadata_reference_table>>. There is no GeoPackage requirement that such metadata be provided or that defined
metadata be structured in a hierarchical fashion footnote:[Informative examples of hierarchical metadata are provided in
<<metadata_example_appendix>>] with more than one level, only that if it is, these tables SHALL be used. Such metadata
footnote:[An informative example of raster image metadata is provided in <<tiles_example_appendix>>] and data that
relates it to GeoPackage contents SHALL NOT be stored in other tables as defined in clause <<_other_data_tables>>.

==== Metadata Table

===== Data

====== Table Definition

________________________________________________________________________________________________________________________
_Req 50:_ A GeoPackage file MAY contain a table named gpkg_metadata. If present it SHALL be defined
per <<gpkg_metadata_cols>> and <<gpkg_metadata_sql>>.
________________________________________________________________________________________________________________________

The first component of GeoPackage metadata is the `gpkg_metadata` table that MAY contain metadata in MIME <<N25>>
encodings structured in accordance with any authoritative metadata specification, such as ISO 19115 <<N40>>,
ISO 19115-2 <<B31>>, ISO 19139 <<B32>>, Dublin Core <<B33>>, CSDGM <<B34>>, DDMS <<B35>>, NMF/NMIS <<B36>>, etc. The
GeoPackage interpretation of what constitutes “metadata” is a broad one that includes UML models <<B37>> encoded in XMI
<<B38>>, GML Application Schemas <<B39>>, ISO 19110 feature catalogues <<B40>>, OWL <<B41>> and SKOS <<B42>> taxonomies,
etc.

[[gpkg_metadata_cols]]
.Metadata Table Definition
[cols=",,,,,",options="header",]
|=======================================================================
|Column Name |Column Type |Column Description |Null |Default |Key
|`id` |integer |Metadata primary key |no | |PK
|`md_scope` |text |Case sensitive name of the data scope to which this metadata applies; see table 11 below |no |‘dataset’ |
|`md_standard_uri` |text |URI reference to the metadata structure definition authority |no |
|`mime_type` |text |MIME [25] encoding of metadata |no |text/xml |
|`metadata` |text |metadata |no |’’
|=======================================================================

The md_standard_uri data value provides an identifier for the metadata structure (schema) specified by its definition
authority. The structure (schema) information could be in whatever encoding is used by the definition authority, e.g.
UML, or IDF, or XML/Schema, or RDF/S.

See <<gpkg_metadata_sql>>.

====== Table Data Values

The `md_scope` column in the `gpkg_metadata` table is the name of the applicable scope for the contents of the metadata
column for a given row. The list of valid scope names and their definitions is provided in Table 11 below. The initial
contents of this table were obtained from the ISO 19115 [40], Annex B B.5.25 MD_ScopeCode code list, which was extended
[^3] for use in the GeoPackage specification by addition of entries with “NA” as the scope code column in Table 10.

.Metadata Scopes
[cols=",,",options="header",]
|=======================================================================
|Name (md_scope) |Scope Code |Definition
|undefined |NA |Metadata information scope is undefined
|fieldSession |012 |Information applies to the field session
|collectionSession |004 |Information applies to the collection session
|series |006 |Information applies to the (dataset) series4
|dataset |005 |Information applies to the (geographic feature) dataset
|featureType |010 |Information applies to a feature type (class)
|feature |009 |Information applies to a feature (instance)
|attributeType |002 |Information applies to the attribute class
|attribute |001 |Information applies to the characteristic of a feature (instance)
|tile |016 |Information applies to a tile, a spatial subset of geographic data
|model |015 |Information applies to a copy or imitation of an existing or hypothetical object
|catalog |NA |Metadata applies to a feature catalog [^5]
|schema |NA |Metadata applies to an application schema [^6]
|taxonomy |NA |Metadata applies to a taxonomy or knowledge system [^7]
|software |013 |Information applies to a computer program or routine
|service |014 |Information applies to a capability which a service provider entity makes available to a service user entity through a set of interfaces that define a behaviour, such as a use case
|collectionHardware |003 |Information applies to the collection hardware class
|nonGeographicDataset |007 |Information applies to non-geographic data
|dimensionGroup |008 |Information applies to a dimension group
|=======================================================================

________________________________________________________________________________________________________________________
*Req {counter:req}:* Each `md_scope` column value in a `gpkg_metadata` table or updateable view SHALL be one of the name column
values from 11 in clause 2.4.2.1.2.
________________________________________________________________________________________________________________________

==== Metadata Reference Table

===== Data

====== Table Definition

________________________________________________________________________________________________________________________
*Req {counter:req}:* A GeoPackage file that contains a gpkg_metadata table SHALL contain a gpkg_metadata_reference table per clause
2.4.3.1.1, Table 12 and Table 34.
________________________________________________________________________________________________________________________

The second component of GeoPackage metadata is the `gpkg_metadata_reference` table that links metadata in the
`gpkg_metadata` table to data in the feature, and tiles tables defined in clauses 2.1.6 and 2.2.7. The
`gpkg_metadata_reference` table is not required to contain any rows.

.Metadata Reference Table or View Definition
[cols=",,,,,",options="header",]
|=======================================================================
|Column Name |Col Type |Column Description |Null |Default |Key
|`reference_scope` |text |Lowercase metadata reference scope; one of ‘geopackage’, ‘table’,‘column’, ’row’, ’row/col’ |no | |
|`table_name` |text |Name of the table to which this metadata reference applies, or NULL for reference_scope of ‘geopackage’. |yes | |
|`column_name` |text |Name of the column to which this metadata reference applies; NULL for `reference_scope` of ‘geopackage’,‘table’ or ‘row’, or the name of a column in the `table_name` table for `reference_scope` of ‘column’ or ‘row/col’ |yes | |
|`row_id_value`[^8] |integer |NULL for `reference_scope` of ‘geopackage’, ‘table’ or ‘column’, or the rowed of a row record in the `table_name` table for `reference_scope` of ‘row’ or ‘row/col’ |yes | |
|`timestamp` |text |timestamp value in ISO 8601 format as defined by the strftime function '%Y-%m-%dT%H:%M:%fZ' format string applied to the current time |no |strftime('%Y-%m-%dT%H:%M:%fZ', CURRENT_TIMESTAMP) |
|`md_file_id` |integer |`gpkg_metadata` table id column value for the metadata to which this `gpkg_metadata_reference` applies |no | |FK
|`md_parent_id` |integer |`gpkg_metadata` table id column value for the hierarchical parent `gpkg_metadata` for the `gpkg_metadata` to which this `gpkg_metadata_reference` applies, or NULL if `md_file_id` forms the root of a metadata hierarchy |yes | |FK
|=======================================================================

Every row in `gpkg_metadata_reference` that has null value as `md_parent_id` forms the root of a metadata hierarchy [^9].

See Annex C: Table Definition SQL clause C.10 `gpkg_metadata_reference`.

====== Table Data Values

________________________________________________________________________________________________________________________
*Req {counter:req}:* Every `gpkg_metadata_reference` table reference scope column value SHALL be one of ‘geopackage’,
‘table’, ‘column’, ’row’, ’row/col’ in lowercase.
________________________________________________________________________________________________________________________

________________________________________________________________________________________________________________________
*Req {counter:req}:* Every `gpkg_metadata_reference` table row with a `reference_scope` column value of ‘geopackage’ SHALL have a
`table_name` column value that is NULL. Every other `gpkg_metadata_reference` table row SHALL have a `table_name` column
value that references a value in the `gpkg_contents` `table_name` column.
________________________________________________________________________________________________________________________

________________________________________________________________________________________________________________________
*Req {counter:req}:* Every `gpkg_metadata_reference` table row with a `reference_scope` column value of ‘geopackage’,‘table’ or
‘row’ SHALL have a `column_name` column value that is NULL. Every other `gpkg_metadata_reference` table row SHALL have a
`column_name` column value that contains the name of a column in the SQLite table or view identified by the `table_name`
column value.
________________________________________________________________________________________________________________________

________________________________________________________________________________________________________________________
*Req {counter:req}:* Every `gpkg_metadata_reference` table row with a `reference_scope` column value of ‘geopackage’, ‘table’ or
‘column’ SHALL have a `row_id_value` column value that is NULL. Every other `gpkg_metadata_reference` table row SHALL
have a `row_id_value` column value that contains the ROWID of a row in the SQLite table or view identified by the
`table_name` column value.
________________________________________________________________________________________________________________________

________________________________________________________________________________________________________________________
*Req {counter:req}:* Every `gpkg_metadata_reference` table row timestamp column value SHALL be in ISO 8601 [41]format containing a
complete date plus UTC hours, minutes, seconds and a decimal fraction of a second, with a ‘Z’ (‘zulu’) suffix indicating
UTC.[^10]
________________________________________________________________________________________________________________________

________________________________________________________________________________________________________________________
*Req {counter:req}:* Every `gpkg_metadata_reference` table row `md_file_id` column value SHALL be an id column value from the
`gpkg_metadata` table.
________________________________________________________________________________________________________________________

________________________________________________________________________________________________________________________
*Req {counter:req}:* Every `gpkg_metadata_reference` table row `md_parent_id` column value that is NOT NULL SHALL be an id column
value from the `gpkg_metadata` table that is not equal to the `md_file_id` column value for that row.
________________________________________________________________________________________________________________________
