=== Extension Mechanism

The GeoPackage extension mechanism is an optional capability that is a required dependency for the optional registered
extension capabilities defined in clause 3.

==== Extensions

===== Data

The optional capabilities defined in sub clauses and requirement statements of this clause MAY be implemented by any
GeoPackage file.

[[extensions_table_definition]]
====== Table Definition

________________________________________________________________________________________________________________________
*Req {counter:req}:* A GeoPackage file MAY contain a table or updateable view named gpkg_extensions. If present this table SHALL be
defined per clause 2.6.1.1.1, Table 13 and Table 23.
________________________________________________________________________________________________________________________

The `gpkg_extensions` table in a GeoPackage file registers extension capabilities required to make direct use of its
contents. An application that access a GeoPackage file can query the `gpkg_extensions` table instead of the contents of
all the user data tables to determine if it has the required capabilitiesto read or write to tables with extensions, and
to “fail fast” and return an error message if it does not.

.GeoPackage Extensions Table or View Definition
[cols=",,,,",options="header",]
|=======================================================================
|Column Name |Col Type |Column Description |Null |Key
|`table_name` |text |Name of the table that requires the extension. When NULL, the extension is required for the entire GeoPackage. SHALL NOT be NULL when the column_name is not NULL. |yes |Unique
|`column_name` |text |Name of the column that requires the extension. When NULL, the extension is required for the entire table. |yes |Unique
|`extension_name` |text |The name of the extension that is required, in the form \_\. |no |Unique
|`scope` |text |Indicates scope of extension effects on readers / writers: 'read-write' or 'write-only'. |no |
|=======================================================================

See Annex C: Table Definition SQL clause C.3 gpkg_extensions.

====== Table Data Values

________________________________________________________________________________________________________________________
*Req {counter:req}:* Values of the `gpkg_extensions` table `table_name` column SHALL reference values in the `gpkg_contents`
`table_name` column or be NULL. They SHALL NOT be NULL for rows where the `column_name` value is not NULL.
________________________________________________________________________________________________________________________

________________________________________________________________________________________________________________________
*Req {counter:req}:* The `column_name` column value in a `gpkg_extensions` table row SHALL be the name of a column in the table
specified by the `table_name` column value for that row, or be NULL.
________________________________________________________________________________________________________________________

________________________________________________________________________________________________________________________
*Req {counter:req}:* Each `extension_name` column value in a `gpkg_extensions` table row SHALL be a unique value of the form \_\
where \ indicates the person or organization that developed and maintains the extension. The valid character set for \
SHALL be [a-zA-Z0-9]. The valid character set for \ SHALL be [a-zA-Z0-9_]. An `extension_name` for the “gpkg” author
name SHALL be one of those listed in Table 14.
________________________________________________________________________________________________________________________

The author value “gpkg” is reserved for GeoPackage extensions that are developed and maintained by OGC. Requirements for
extension names for the “gpkg” author name are defined in the clauses listed in 14 below. GeoPackage implementers use
their own author names to register other extensions.1

.Reserved GeoPackage Extensions
[cols=",,",options="header",]
|=======================================================================
|Extension Name |Defined in Clause |Scope | Description
|gpkg_geom_\<gname\> |3.1.2.1.2 |read-write |\<gname\> is name of specific extension geometry type from Annex G 47
|gpkg_zoom_other |3.2.1.1.1 |read-write |Tile matrix set user data table with zoom intervals other than powers of two between adjacent layers
|gpkg_webp |3.2.2.2.1 |read-write |Raster images in image/webp format
|gpkg_tiff |3.2.3.1.2 |read-write |Raster images in image/tiff format
|gpkg_nitf |3.2.4.1.2 |read-write |Raster images in application/vnd.NITF
|gpkg_rtree_index |3.1.3.1.2 |write-only |Rtree spatial index implemented via SQLite Virtual Table and maintained via triggers that use all minimal runtime SQL functions except ST_SRID.
|gpkg_gtype_trigger |3.1.4.1.2 |write-only |Trigger to restrict GeoPackage feature table geometry column geometries to geometry types equal to or substitutable for the geometry type specified for the column in the `gpkg_geometry_columns` table `geometry_type_name` column.
|gpkg_srs_id_trigger |3.1.5.1.2 |write-only |Trigger to restrict GeoPackage feature table geometry column geometries to the `srs_id` specified for the geometry column in the `gpkg_geometry_columns` table using the ST_SRID SQL function.
|=======================================================================

===== API

The optional capabilities defined in sub clauses and requirement statements of this clause MAY be implemented by any
GeoPackage SQLite Extension.

====== API GeoPackage SQLite Config

________________________________________________________________________________________________________________________
*Req {counter:req}:* A GeoPackage SQLite Extension MAY provide SQL runtime functions or rtree support for a GeoPackage file. One
that does so SHALL have the SQLite library compile and run time options specified in clause 2.6.1.2.1 Table 15
________________________________________________________________________________________________________________________

.API GeoPackage SQLite Configuration
[cols=",,,",options="header",]
|=======================================================================
|Setting |Option |Shall / Not (Value) |Discussion
|compile |SQLITE_OMIT_LOAD_EXTENSION |Not |The load_extension() function is required to implement the MinimalRuntimeSQLFunctions
|compile |SQLITE_OMIT_VIRTUALTABLE |Not |Virtual tables are required to implement RTrees
|compile |SQLITE_ENABLE_RTREE |Shall |Rtrees are used for GeoPackage Spatial Indexes. See SpatialIndexRequirements
|compile |SQLITE_RTREE_INT_ONLY |Not |Rtrees with floating point values are used for GeoPackage Spatial Indexes.
|=======================================================================

====== Safe GeoPackage SQLite Config

________________________________________________________________________________________________________________________
*Req {counter:req}:* A GeoPackage SQLite Extension MAY provide primary/foreign key and trigger support for a GeoPackage file. One
that does so SHALL have the SQLite library compile and run time options specified in clause 2.6.1.2.2 Table 16.
________________________________________________________________________________________________________________________

.Safe GeoPackage SQLite Configuration
[cols=",,,",options="header",]
|=======================================================================
|Setting |Option |Shall / Not (Value) |Discussion
|compile |SQLITE_DEFAULT_FOREIGN_KEYS |Shall (1)
|Foreign key constraints are used to maintain GeoPackage relational integrity.
|compile |SQLITE_OMIT_FOREIGN_KEY |Not
|Foreign key constraints are used to maintain GeoPackage relational integrity.
|run |PRAGMA foreign_keys |Not (OFF)
|Foreign key constraints are used to maintain GeoPackage relational integrity.
|compile |SQLITE_OMIT_INTEGRITY_CHECK |Not
|This option omits support for the integrity_check pragma, which does an integrity check of the entire database. This
pragma should be part of GeoPackage conformance validation.
|compile |SQLITE_OMIT_SUBQUERY |Not
|This option omits support for sub-selects and the IN() operator, both of which are used in GeoPackage triggers.
|compile |SQLITE_OMIT_TRIGGER |Not
|Defining this option omits support for TRIGGER objects. Neither the CREATE TRIGGER or DROP TRIGGER commands are
available in this case, and attempting to execute either will result in a parse error. This option also disables
enforcement of foreign key constraints, since the code that implements triggers and which is omitted by this option is
also used to implement foreign key actions. Foreign keys and triggers are used by Safe GeoPackages. Triggers are used to
maintain spatial indexes.
|=======================================================================

