[[Clause_Substantive]]
== Description of Substantive Changes

There are four substative changes incorproated into the GeoPackage Tiled Gridded Coverage Version 1.1 extension. These changes do not inpact backwards compatibility.

=== https://github.com/opengeospatial/geopackage/issues/552[Issue 552]: Request ability to support additional data types in GeoPackage coverages.

A synopsis of the issue and related suggested changes is:

The CDB SWG is considering the use of GeoPackage to store coverage data as component of CDB 2.0. CDB currently uses a variety of data element types (in GeoTiff) to store coverage data. Therefore, the CDB SWG is requesting being able to use these data types in a GeoPackage coverage tile:

    8/16/32 bit signed integers
    8 bit unsigned integer (16-bit integer is currently supported, but only for PNG)
    32-bit floating point (already supported in GeoPackage coverages)
    1 bit (will be used in CDB 1.2 when adopted, as a binary mask)

I think it would benefit the GeoPackage format to allow the use of GeoPackage coverages beyond a few narrow use cases that the existing formats allow.

=== https://github.com/opengeospatial/geopackage/issues/553[Issue 553]: Request enabling the use of multiple channels in a GeoPackage Coverage

A synopsis of the issue and related suggested changes is: 

Using a single channel coverage can cover many data types and use cases, but not all. In particular, there are data coverages that are comprised of multiple data values per grid cell, and designed such that all the data elements to make use of this type of data are needed. For example, a layer that describes current wind conditions would be defined by both wind cardinal direction and velocity. In this example, using either coverage without the other would be very difficult.

In the CDB Standard, there are coverages that represent the physical material of a grid on the ground or on a model. These coverages consist of the material index and a percentage of that material. Another use case is encoding elevation data based on a point elevation (not an average), where at lower resolutions we want to adjust the point's position (in latitude/longitude) as offsets from the grid cell corner.

If coverages were more flexible in this manner, then imagery could just become another coverage, and possibly also contain non-visual bands (like Near Infrared (NIR) or Short-Wave Infrared (SWIR) data).

=== https://github.com/opengeospatial/geopackage/issues/576[Issue 576]: Clarify existing requirements classes

A synopsis of the issue is and related changes are: 

Right now there is a lack of precision in some of the TGCE requirements classes. Also there are currently too many requirements classes. The current set of requirements classes can be consolidated into two requirements classes and related conforance classes:
    Core (Requirements 1-13 / Section 7)
    TIFF Encoding (Requirements 14-21 / Section 8)

Therefore Requirement 14 needs to get moved into the TIFF Encoding Requirements Class and rewritten in such a way that it can be supplanted by a more flexible (but harder to implement) Requirements Class as described in issues #552 and #553 (See above).

The SWG discussed and approved the changes necessary to resolve this issue.
