== Terms and definitions

This document uses the terms defined in Sub-clause 5.3 of [OGC 06-121r8], which is based on the ISO/IEC Directives, Part 2, Rules for the structure and drafting of International Standards. In particular, the word “shall” (not “must”) is the verb form used to indicate a requirement to be strictly followed to conform to this standard.

For the purposes of this document, the following additional terms and definitions apply.

===	administrative change
An administrative change is a change that does not alter the conformance abstract tests for any requirements. It includes typographical errors, changes in wording to improve clarity or consistency, and perfunctory changes such as changes in version numbers.

=== critical Change
A critical change is a change that alters requirements in a way that is known to cause reverse compatibility issues.

=== substantive change
A substantive change is a change that alters requirements or schemas in a way that is not deemed to have a high risk for causing reverse compatibility issues.

===	Abbreviated terms

//List any abbreviations and their full expansions that are used in this document
