[[Clause_Substantive]]
== Description of Substantive Changes

There are four substative changes incorproated into the GeoPackage Tiled Gridded Coverage Version 1.1 extension. These changes do not inpact backwards compatibility.

=== https://github.com/opengeospatial/geopackage/issues/552[Issue 552]: Request ability to support additional data types in GeoPackage coverages.

=== https://github.com/opengeospatial/geopackage/issues/553[Issue 553]: Request enabling the use of multiple channels in a GeoPackage Coverage

=== https://github.com/opengeospatial/geopackage/issues/576[Issue 576]: Clarify existing requirements classes

A synopsis of the issue and related suggested changes is: 

Right now there is a lack of precision in some of the TGCE requirements classes. Also there are currently too many requirements classes. The current set of requirements classes can be consolidated into two requirements classes and related conforance classes:
    Core (Requirements 1-13 / Section 7)
    TIFF Encoding (Requirements 14-21 / Section 8)

Therefore Requirement 14 needs to get moved into the TIFF Encoding Requirements Class and rewritten in such a way that it can be supplanted by a more flexible (but harder to implement) Requirements Class as described in issues #552 and #553 (See above).

The SWG discussed and approved the changes necessary to resolve this issue.
