[[Clause_Substantive]]
== Description of Substantive Changes

There are two substantive changes incorporated into the GeoPackage Tiled Gridded Coverage Version 1.1 extension. These changes do not impact backwards compatibility.

=== https://github.com/opengeospatial/geopackage/issues/552[Issue 552]: Request ability to support additional data types in GeoPackage coverages.

A synopsis of the issue and related suggested changes is:

The CDB SWG is considering the use of GeoPackage to store coverage data as component of CDB 2.0. CDB currently uses a variety of data element types (in GeoTiff) to store coverage data. Therefore, the CDB SWG is requesting being able to use these data types in a GeoPackage coverage tile:

    8/16/32 bit signed integers
    8 bit unsigned integer (16-bit integer is currently supported, but only for PNG)
    32-bit floating point (already supported in GeoPackage coverages)
    1 bit (will be used in CDB 1.2 when adopted, as a binary mask)

Therefore there is benefit to allowing the use of GeoPackage coverages beyond a few narrow use cases that the existing formats allow.

=== https://github.com/opengeospatial/geopackage/issues/576[Issue 576]: Clarify existing requirements classes

A synopsis of the issue is and related changes are: 

Right now there is a lack of precision in some of the TGCE requirements classes. Also there are currently too many requirements classes. The current set of requirements classes can be consolidated into two requirements classes and related conformance classes:
    Core (Requirements 1-13 / Section 7)
    TIFF Encoding (Requirements 14-21 / Section 8)

Therefore Requirement 14 needs to get moved into the TIFF Encoding Requirements Class and rewritten in such a way that it can be supplanted by a more flexible (but harder to implement) Requirements Class as described in issues #552 and #553 (See above).

The SWG discussed and approved the changes necessary to resolve this issue.
