== Requirements (Normative)
=== Table Definition
==== gpkg_spatial_ref_sys
[[r115]]
[caption=""]
.Requirement 115
====
For GeoPackages conforming to this extension, the `gpkg_spatial_ref_sys` table SHALL have additional columns called `definition_12_063` and `epoch` as per <<gpkg_spatial_ref_sys_cols_crs_wkt>> and <<gpkg_spatial_ref_sys_crs_wkt_sql>>.
====

[#gpkg_spatial_ref_sys_cols_crs_wkt,reftext='{table-caption} {counter:table-num}']
.Spatial Ref Sys Table Definition
[cols=",,,,",options="header",]
|====
|Column Name |Column Type |Column Description |NOT NULL flag |Key
|`srs_name` |TEXT |Human readable name of this SRS |true |
|`srs_id` |INTEGER |Unique identifier for each Spatial Reference System within a GeoPackage |true |PK
|`organization` |TEXT |Case-insensitive name of the defining organization e.g. EPSG or epsg |true |
|`organization_coordsys_id` |INTEGER |Numeric ID of the Spatial Reference System assigned by the organization |true |
|`definition` |TEXT |Well-known Text <<I32>> Representation of the Spatial Reference System |true|
|`description` |TEXT |Human readable description of this SRS |false|
|`definition_12_063` |TEXT |Well-known Text <<I34>> or <<I36>> Representation of the Spatial Reference System |true|
|`epoch` |DOUBLE |Coordinate epoch as per https://docs.opengeospatial.org/as/18-005r4/18-005r4.html#68 |false|
|====

[NOTE]
====
Previous versions of this extension specified default values for `definition` and `definition_12_063`. Those defaults have been removed for interoperability reasons but implementers should be aware that some GeoPackages may have these defaults in place.
====

=== Table Data Values

==== gpkg_extensions
[[r145]]
[caption=""]
.Requirement 145
====
GeoPackages with a row in the `gpkg_extensions` table with an `extension_name` of "gpkg_crs_wkt" SHALL comply with the extension defined in this Standard.
GeoPackages complying with this extension SHALL have the rows in the `gpkg_extensions` table specified in <<CRSWKTExtensionTableRecord>> (below).
====

[WARNING]
=====
Requirement 145 has been updated as part of GeoPackage 1.2.1.
In 1.1.0 and 1.2.0, the `table_name` and `column_name` column values of the required `gpkg_extensions` row were inadvertently left unspecified.
While the executable test suite running on an older GeoPackage version will not generate a failure due to missing `gpkg_extensions` column values, implementers are encouraged to update these values to comply with the updated requirement on older versions as well.
=====

[#CRSWKTExtensionTableRecord,reftext='{table-caption} {counter:table-num}']
.Extension Table Records
[cols=",,,,",options="header",]
|====
|*table_name* |*column_name* |*extension_name* |*definition* |*scope*
|`gpkg_spatial_ref_sys` |`definition_12_063` |`gpkg_crs_wkt` |_see note below_|`read-write`
|`gpkg_spatial_ref_sys` |`definition_12_063` |`gpkg_crs_wkt_1_1` |_see note below_|`read-write`
|`gpkg_spatial_ref_sys` |`epoch` |`gpkg_crs_wkt_1_1` |_see note below_|`read-write`
|====

[NOTE]
=====
For the `definition` column, use a hyperlink that describes the current implementation of this extension.
While a URL such as http://www.geopackage.org/spec/#extension_crs_wkt is acceptable, permalinks to specific versions are provided upon publication using the URL pattern http://www.geopackage.org/specMmP/#extension_crs_wkt where `M` is the major version, `m` is the minor version, and `P` is the patch. For example http://www.geopackage.org/spec121/#extension_crs_wkt is the permalink for this extension for GeoPackage 1.2.1.
=====

==== gpkg_spatial_ref_sys
[[r116]]
[caption=""]
.Requirement 116
====
Values of the `definition_12_063` column SHALL be constructed per the WKT syntax as defined in <<I34>> and <<I36>>.
====

[NOTE]
====
For backwards compatibility, only use WKT values that are common to both 12-063 and 18-010.
Additional WKT values specified in 18-010r7 can be used when required in the CRS definition.
====


[[r117]]
[caption=""]
.Requirement 117
====
At least one definition column SHALL be defined with a valid definition unless the value of the `srs_id` column is `0` or `-1`. Both columns SHOULD be defined. If it is not possible to produce a valid <<I32>> definition then the value of the `definition` column MAY be `undefined`. If it is not possible to produce a valid <<I34>> or <<I36>> definition then the value of the `definition_12_063` column MAY be `undefined`.
====

[NOTE]
====
. If, for a particular row, both the `definition` and `definition_12_063` columns are populated, the value in the `definition_12_063` column takes priority.
. The coordinate epoch SHOULD be provided if available. As such, a GeoPackage could have multiple SRSs with the same `organization` and `organization_coordsys_id` but with different epochs. While the epoch should theoretically go in the dataset metadata (per ISO 19111 / OGC Topic 2 as approved by the OGC in March 2021), there is not currently a standard metadata profile that would be suitable.
====
