== Terms and Definitions
This document used the terms defined in https://portal.ogc.org/public_ogc/directives/directives.php[OGC Policy Directive 49], which is based on the ISO/IEC Directives, Part 2, Rules for the structure and drafting of International Standards. In particular, the word “shall” (not “must”) is the verb form used to indicate a requirement to be strictly followed to conform to this standard and OGC documents do not use the equivalent phrases in the ISO/IEC Directives, Part 2.

This document also uses terms defined in the OGC Standard for Modular specifications (https://portal.opengeospatial.org/files/?artifact_id=34762[OGC 08-131r3]), also known as the 'ModSpec'. The definitions of terms such as standard, specification, requirement, and conformance test are provided in the ModSpec.

For the purposes of this document, the following additional terms and definitions apply.

coordinate epoch::
A property of a dynamic coordinate reference system indicating the date at which the coordinates are valid. (SOURCE: OGC 18-005r4)

Coordinate Reference System (CRS)::
A coordinate reference system, or spatial reference system (SRS), is a set of mathematical rules for specifying how coordinates are to be assigned to points that is related to an object by a datum. (SOURCE: ISO 19111:2019) 

[NOTE]
====
The GeoPackage Encoding Standard (GES) uses the term "spatial reference system." In the GES, a spatial reference system is realized through a `gpkg_spatial_ref_sys` row.
====

well-known text (WKT)::
A compact machine- and human-readable representation of geometric objects that may also be used for succinctly describing the critical elements of CRS definitions. (SOURCE: OGC 18-020r7)

[NOTE]
====
CRS WKT2 specifically refers to a document conforming to OGC 18-010r7.
====