[appendix]
[[abstract_test_suite]]
== Conformance / Abstract Test Suite (Normative)

===	Base

====	Core

=====	SQLite Container

======	Data

=======	File Format

[cols="1,5"]
Test Case ID| /base/core/container/data/file_format
Test Purpose| Verify that the Geopackage is an SQLite version_3 database
Test Method| Pass if the first 16 bytes of the file contain “SQLite format 3” in ASCII.
Reference| Clause 1.1.1.1.1 Req 1:
Test Type| Basic

[cols="1,5"]
Test Case ID| /base/core/container/data/file_format/application_id
Test Purpose| Verify that the SQLite database header application id field indicates GeoPackage version 1.0
Test Method| Pass if the application id field of the SQLite database header contains “GP10” in ASCII.
Reference| Clause 1.1.1.1.1 Req 2:
Test Type| Basic

=======	File Extension Name

[cols="1,5"]
Test Case ID| /base/core/container/data/file_extension_name
Test Purpose| Verify that the geopackage extension is ".gpkg"
Test Method| Pass if the geopackage file extension is ".gpkg"
Reference| Clause 1.1.1.1.2 Req 3:
Test Type| Basic

