[[extension_geometry_srsid_triggers]]
=== Geometry SRS ID Triggers 

[float]
==== Introduction

This extension adds a new srs_id triggers capability for columns with geometries encoded per clause <<gpb_format>> and <<extension_geometry_encoding>>.

Geometry SRS_ID triggers prevent the storage of geometries with spatial reference system identifiers that are not specified in the `gpkg_geometry_columns` table in the geometry columns of the specified tables.

[float]
==== Extension Author

GeoPackage SWG, author_name `gpkg`.

[float]
==== Extension Name or Template

`gpkg_srs_id_trigger`

[float]
==== Extension Type

New Requirement dependent on clauses <<gpb_format>> and 3.1.2.

[float]
==== Applicability

This extension applies to any column specified in the gpkg_geometry_columns table.

[float]
==== Scope

Write-only

[float]
==== Requirements

[float]
===== GeoPackage

[requirement]
The “gpkg_srs_id_trigger” extension name SHALL be used as a gpkg_extensions table extension name column value to specify implementation of SRS_ID triggers specified in <<extension_geometry_srsid_triggers>>.

[requirement]
A GeoPackage that implements srs_id triggers on feature table geometry columns SHALL contain a gpkg_extensions table that contains a row for each geometry column with extension_name “gpkg_srs_id_trigger”, table_name of the feature table with a geometry column, and column_name of the geometry column.

[requirement]
A GeoPackage SHALL include the SQL insert and update triggers specified in <<extension_geometry_srsid_triggers>> on every geometry column to enforce the srs_id values specified for those columns in the `gpkg_geometry_columns` table.

The <t> and <c> template parameters in the SRS_ID trigger definition SQL template in the table below are to be replaced with the names of the feature table and geometry column being inserted or updated

[source,sql]
----
CREATE TRIGGER fgsi_<t> _<c> BEFORE INSERT ON '<t>' FOR EACH ROW
BEGIN
  SELECT RAISE (ABORT, 'insert on <t>violates constraint: ST_SRID(<c>) does not match gpkg_geometry_columns.srs_id value')
  WHERE (SELECT srs_id FROM gpkg_geometry_columns
         WHERE Lower(table_name) = Lower('<t>')
	       AND   Lower(column_name) = Lower('<c>')
	       AND   ST_SRID(NEW.'<c>') <> srs_id) ;
END

CREATE TRIGGER fgsu_<t>_<c> BEFORE UPDATE OF '<c>' ON '<t>' FOR EACH ROW
BEGIN
  SELECT RAISE (ABORT, 'update of <c> on <t> violates constraint: ST_SRID(<c>) does not match gpkg_geometry_columns.srs_id value')
  WHERE (SELECT srs_id FROM gpkg_geometry_columns
         WHERE Lower(table_name) = Lower('<t>')
	       AND   Lower(column_name) = Lower('<c>')
	       AND   ST_SRID(NEW.'<c>') <> srs_id);
END
----

[float]
===== GeoPackage SQLite Configuration

None

[float]
===== GeoPackage SQLite Extension

Definition of SQL functions

[cols=",,,",options="header"]
|======
|SQL Function |Description |Use
|ST_SRID(geom. Geometry) : INTEGER |Returns the spatial reference system id of a Geometry |Check that geometry srid matches what's specified in `gpkg_geometry_columns.srid`
|======

[requirement]
The SQL function on geometries in this SQLite Extension SHALL operate correctly on extended geometry types specified by Annex J and/or Annex K when those extensions are also implemented.