[[extension_tiled_gridded_elevation_data]]
=== Tiled Gridded Elevation Data

[WARNING]
=====================
On May 2, 2017 the OGC Architecture Board (OAB) voted to remove this extension from the this draft standard document so that it can be worked on separately. This subannex will remain here temporarily but will be removed once a new draft document is established.
=====================

[float]
==== Extension Title

Tiled Gridded Elevation Data

[float]
==== Introduction

This extension provides the ability to store 16-bit and 32-bit tiled gridded elevation data in a GeoPackage. This capability will be used to support use cases such as the following:

* Visualization
**  2D (hillshade, color relief, slope)
**  3D (supporting changing view angles and level of detail)
* Analysis
**  Viewshed and line-of-sight
** Cross-country mobility (off-road routing)
** Site suitability and planning (slope analysis such as helicopter landing zones)
** 3D geometry representations of features (ground-based, airspace)
**  Terrain association (associating images to mapped locations)
**  Augmented reality training

:elevation_precision: footnote:[We acknowledge that this approach will not support certain applications that require a high degree of precision and/or accuracy (e.g., targeting).]
This capability was designed to be relatively easy to implement and to be suitable for a wide variety of computing environments including the mobile/handheld computing environment{elevation_precision}.

This extension to the OGC GeoPackage Encoding Standard leverages the existing structure for raster tiles using PNG (16-bit) and TIFF (32-bit) files as the container for the elevation values themselves. It is the data producer's responsibility to ensure that the intended recipient is able to read GeoPackages with the elevation encoding (PNG or TIFF) being used. By default, the elevation values are assumed to be average elevation for pixel-is-area. Communities of interest may agree to use an alternative pixel encoding (such as pixel-is-point) but specifying the pixel encoding is outside of the scope of this document.

[float]
==== Extension Author

GeoPackage SWG, author_name `gpkg`.

[float]
==== Extension Name or Template

`gpkg_elevation_tiles`

[float]
==== Extension Type

New requirement dependent on http://www.geopackage.org/spec/#tiles[Clause 2.2].

[float]
==== Applicability

This extension applies to http://www.geopackage.org/spec/#tiles_user_tables[tile pyramid user data tables] that are used to hold tiled, gridded elevation data.

[float]
==== Scope

read-write

[float]
==== Requirements

[float]
===== Table Definitions
[[coverage_ancillary]]

[float]
====== Coverage Ancillary

[[r120]]
[caption=""]
.Requirement 120
====
A GeoPackage that contains tiled gridded elevation data SHALL contain a `gpkg_2d_gridded_coverage_ancillary` table or view as per <<gpkg_2d_gridded_coverage_ancillary_table>>.
Subsequent extensions or custom implementations MAY add additional columns to this table.
Clients SHALL ignore additional columns that are unrecognized.
====

:real_value: footnote:[This is a REAL to support extensions that use non-integer data.]
[[gpkg_2d_gridded_coverage_ancillary_table]]
.Coverage Ancillary Table Definition
[cols=",,,,,,",options="header",]
|=======================================================================
|Column Name |Column Type |Column Description |Null |Default |Key|Constraint
|`id`|INTEGER |Autoincrement primary key|no||PK|
|`tile_matrix_set_name`|TEXT|Foreign key to `table_name` in http://www.geopackage.org/spec/#tile_matrix_set_data_table_definition[`gpkg_tile_matrix_set`]|no||FK|UNIQUE
|`datatype`|TEXT  |_integer_ or _float_|no|_integer_||
|`scale`|REAL|Scale as a multiple relative to the unit of measure|no|1||
|`offset`|REAL|The offset to the 0 value|no|0||
|`precision`|REAL{real_value}|The smallest value that has meaning for this dataset|yes|1||
|`data_null`|REAL{real_value}|The value that indicates NULL|yes|||
|=======================================================================

[float]
====== Using the Scale and Offset Values
Integer elevation values MAY be scaled and offset in order to make more efficient use of 16-bit integer space available in PNG files. The scale and offset MAY be applied to the entire coverage and/or the individual tile. The scale and offset do not apply to the `data_null` value as defined in <<gpkg_2d_gridded_coverage_ancillary_table>>.

Actual elevation values are be calculated by:

* first multiplying the stored value by the `gpkg_2d_gridded_tile_ancillary_table.scale` value and then adding the `gpkg_2d_gridded_tile_ancillary_table.offset`,
* followed by multiplying that value by the `gpkg_2d_gridded_coverage_ancillary.scale` value and then adding the `gpkg_2d_gridded_coverage_ancillary.offset`.

In pseudo-code, this conversion would look like:

    elevationInUnitOfMeasure = (SomeElevationCoverage.tile_data->pngpixels[i] * gpkg_2d_gridded_tile_ancillary.scale + gpkg_2d_gridded_tile_ancillary.offset) * gpkg_2d_gridded_coverage_ancillary.scale + gpkg_2d_gridded_coverage_ancillary.offset;

Note: _integer_ and _float_ refer to the values stored in the tiles. If _integer_ values have a real scale or offset applied to them, then the resulting values will be real. The `scale` and `offset` do not apply to tiles of datatype _float_.

[float]
====== Tile Ancillary
[[r121]]
[caption=""]
.Requirement 121
====
A GeoPackage that contains tiled gridded elevation data SHALL contain a `gpkg_2d_gridded_tile_ancillary` table or view as per <<gpkg_2d_gridded_tile_ancillary_table>>.
Subsequent extensions or custom implementations MAY add additional columns to this table.
Clients SHALL ignore additional columns that are unrecognized.
====

:jointly_unique: footnote:[These two values are designed to be jointly unique so that they refer to a single row in a single table.]
[[gpkg_2d_gridded_tile_ancillary_table]]
.Tile Ancillary Table Definition
[cols=",,,,,",options="header",]
|=======================================================================
|Column Name |Column Type |Column Description |Null |Default |Key
|`id`|INTEGER |Autoincrement primary key|no||PK
|`tpudt_name`|TEXT  |Name of http://www.geopackage.org/spec/#tiles_user_tables[tile pyramid user data table]|no||UNIQUE{jointly_unique}
|`tpudt_id`|INTEGER |Foreign key to `id` in http://www.geopackage.org/spec/#tiles_user_tables[tile pyramid user data table]|no||UNIQUE{jointly_unique}
|`scale`|REAL|Scale as a multiple relative to the unit of measure|no|1|
|`offset`|REAL|The offset to the 0 value|no|0|
|`min`|REAL{real_value}|Minimum value of this tile|yes||
|`max`|REAL{real_value}|Maximum value of this tile|yes||
|`mean`|REAL|The arithmetic mean of values in this tile|yes||
|`std_dev`|REAL|The standard deviation of values in this tile|yes||
|=======================================================================

The `min`, `max`, and `mean` values are natural, i.e., not scaled or offset. Similarly, the `std_dev` is calculated based on the natural values. The `scale` and `offset` do not apply to tiles of datatype _float_.

[float]
===== Table Values

[float]
====== gpkg_spatial_ref_sys
[[r122]]
[caption=""]
.Requirement 122
====
GeoPackages complying with this extension SHALL have a row in the `gpkg_spatial_ref_sys` table as described in <<gpkg_spatial_ref_sys_record>>:
====

Because of limitations in expressing 3D coordinate reference systems in Well-known Text <<32>>, it is recommended that GeoPackages complying with this extension also comply with <<extension_crs_wkt>>.

[[gpkg_spatial_ref_sys_record]]
.Spatial Ref Sys Table Record
[cols=",,,,",options="header",]
|=======================================================================
|`srs_name`|`srs_id`|`organization`|`organization_coordsys_id`|`definition`|`description`
|any|`4979`|`EPSG` or `epsg`|`4979`|any|any
|=======================================================================

[[r123]]
[caption=""]
.Requirement 123
====
The `gpkg_spatial_ref_sys` table in a GeoPackage SHALL contain records to define all spatial reference systems used by tiled gridded elevation data in a GeoPackage. The spatial reference system SHALL be used to define the vertical datum, reference geoid, and units of measure for the tiled gridded elevation data.
====

[float]
====== gpkg_contents
:vertical_datum: footnote:[Ideally the vertical datum for each pyramid of elevation will be specified. However, it is impractical to mandate this for a number of reasons, including the difficulty in testing whether a specific SRS has a valid vertical datum.]
[[r124]]
[caption=""]
.Requirement 124
====
(extends http://www.geopackage.org/spec/#r34[GPKG-34]) The http://www.geopackage.org/spec/#_contents[`gpkg_contents`] table SHALL contain a row with a `data_type` column value of '2d-gridded-coverage' for each tile pyramid containing tiled gridded elevation data. The `srs_id` column value for that row SHOULD reference an SRS that has a vertical datum{vertical_datum}.
====

[float]
====== gpkg_extensions
[[r125]]
[caption=""]
.Requirement 125
====
GeoPackages complying with this extension SHALL have rows in the `gpkg_extensions` table as described in <<gpkg_extensions_records>>.
====

[[gpkg_extensions_records]]
.Extensions Table Record
[cols=",,,,",options="header",]
|=======================================================================
|`table_name`|`column_name`|`extension_name`|`definition`|`scope`
|gpkg_2d_gridded_coverage_ancillary|null|`gpkg_elevation_tiles`|http://www.geopackage.org/spec/#extension_tiled_gridded_elevation_data|`read-write`
|gpkg_2d_gridded_tile_ancillary|null|`gpkg_elevation_tiles`|http://www.geopackage.org/spec/#extension_tiled_gridded_elevation_data|`read-write`
|name of actual http://www.geopackage.org/spec/#tiles_user_tables[tile pyramid user data table] containing elevation data|`tile_data`|`gpkg_elevation_tiles`|http://www.geopackage.org/spec/#extension_tiled_gridded_elevation_data|`read-write`
|=======================================================================

[float]
====== gpkg_2d_gridded_coverage_ancillary
The following requirements refer to the `gpkg_2d_gridded_coverage_ancillary` table as per <<gpkg_2d_gridded_coverage_ancillary_table>>.

[[r126]]
[caption=""]
.Requirement 126
====
For each row in `gpkg_contents` with a `data_type` column value of '2d-gridded-coverage', there SHALL be a row in `gpkg_2d_gridded_coverage_ancillary`. Values of the `tile_matrix_set_name` column SHALL reference values in the `gpkg_contents` `table_name` column.
====

[[r127]]
[caption=""]
.Requirement 127
====
Values of the `gpkg_2d_gridded_coverage_ancillary` `tile_matrix_set_name` column SHALL reference values in the `gpkg_tile_matrix_set` `table_name` column.
====

[[r128]]
[caption=""]
.Requirement 128
====
Values of the `gpkg_2d_gridded_coverage_ancillary` `datatype` column MAY be _integer_ or _float_. When the `datatype` is _float_, the `scale` and `offset` values SHALL be set to the defaults.
====

[float]
====== gpkg_2d_gridded_tile_ancillary
The following requirements refer to the `gpkg_2d_gridded_tile_ancillary` table as per <<gpkg_2d_gridded_tile_ancillary_table>>.

[[r129]]
[caption=""]
.Requirement 129
====
For each row in a tile pyramid user data table corresponding to tiled, gridded elevation data, there SHALL be a row in `gpkg_2d_gridded_tile_ancillary`.
====

[[r130]]
[caption=""]
.Requirement 130
====
Values of the `gpkg_2d_gridded_tile_ancillary` `tpudt_name` column SHALL reference existing http://www.geopackage.org/spec/#tiles_user_tables[tile pyramid user data tables] and rows in `gpkg_2d_gridded_coverage_ancillary`. When the `datatype` of the corresponding `gpkg_2d_gridded_coverage_ancillary` row is _float_, the `scale` and `offset` values SHALL be set to the defaults.
====

[[r131]]
[caption=""]
.Requirement 131
====
Values of the `gpkg_2d_gridded_tile_ancillary` `tpudt_id` column SHALL reference values in `id` column of the table referenced in `tpudt_name`.
====

[float]
====== Tile Pyramid User Data Tables
[[r132]]
[caption=""]
.Requirement 132
====
For data where the `datatype` column of the corresponding row in the `gpkg_2d_gridded_coverage_ancillary` table is _integer_, the `tile_data` BLOB in the http://www.geopackage.org/spec/#tiles_user_tables[tile pyramid user data table] containing tiled, gridded elevation data SHALL be of http://www.ietf.org/rfc/rfc2046.txt[MIME type] `image/png` and the data SHALL be 16-bit unsigned integer (single channel - "greyscale").
====

[[r133]]
[caption=""]
.Requirement 133
====
(extends http://www.geopackage.org/spec/#r36[GPKG-36] and http://www.geopackage.org/spec/#r37[GPKG-37]) For data where the `datatype` column of the corresponding row in the `gpkg_2d_gridded_coverage_ancillary` table is _float_, the `tile_data` BLOB in the http://www.geopackage.org/spec/#tiles_user_tables[tile pyramid user data table] containing tiled, gridded elevation data SHALL be of http://www.ietf.org/rfc/rfc2046.txt[MIME type] `image/tiff` and the data SHALL be 32-bit floating point as described by the TIFF Encoding (<<tiff_encoding>>).
====

[float]
==== Table Definition SQL

[[gpkg_coverage_ancillary_sql]]
.Coverage Ancillary Table Definition SQL
[cols=","]
[source,sql]
----
CREATE TABLE 'gpkg_2d_gridded_coverage_ancillary' (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  tile_matrix_set_name TEXT NOT NULL UNIQUE,
  datatype TEXT NOT NULL DEFAULT 'integer',
  scale REAL NOT NULL DEFAULT 1.0,
  offset REAL NOT NULL DEFAULT 0.0,
  precision REAL DEFAULT 1.0,
  data_null REAL,
  CONSTRAINT fk_g2dgtct_name FOREIGN KEY('tile_matrix_set_name') REFERENCES gpkg_tile_matrix_set ( table_name )
  CHECK (datatype in ('integer','float')));
----

[[gpkg_tile_ancillary_sql]]
.Tile Ancillary Table Definition SQL
[cols=","]
[source,sql]
----
CREATE TABLE gpkg_2d_gridded_tile_ancillary (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  tpudt_name TEXT NOT NULL,
  tpudt_id INTEGER NOT NULL,
  scale REAL NOT NULL DEFAULT 1.0,
  offset REAL NOT NULL DEFAULT 0.0,
  min REAL DEFAULT NULL,
  max REAL DEFAULT NULL,
  mean REAL DEFAULT NULL,
  std_dev REAL DEFAULT NULL,
  CONSTRAINT fk_g2dgtat_name FOREIGN KEY (tpudt_name) REFERENCES gpkg_contents(table_name),
  UNIQUE (tpudt_name, tpudt_id));
----

[float]
[[tiff_encoding]]
===== TIFF Encoding
Because of the wide range of possible TIFF encodings, the TIFF encoding for an elevation tile has been constrained for the sake of interoperability and best practice. Each TIFF encoded tile is a baseline TIFF as defined in the Part 1 of TIFF<<35>>. The only allowed encoding extensions are:

* IEEE floating point (see <<r136>>)
* LZW compression (see <<r137>>)

Tiles are encoded as a single-band image using one 32-bit floating point component per pixel. This implies a number of constraints which are listed below:

* There is only one band per TIFF tile, i.e., for any pixel in the TIFF tile, there SHALL be only one component  (see <<r135>>).
* All pixels in the tile SHALL be set with a valid component value (see <<r143>>).
* Other TIFF tags are derived from the other constraints in this extension. 
* No multi-image/tiling extensions defined in TIFF<<35>> shall be used (see <<r138>>, <<r139>>).

[[r134]]
[caption=""]
.Requirement 134
====
A TIFF file used for storing tiled gridded elevation data SHALL conform to the TIFF specification <<35>>.
====

[[r135]]
[caption=""]
.Requirement 135
====
(constrains TIFF<<35>> Section 2) A TIFF file storing tiled gridded elevation data SHALL have one sample per pixel.
====

By setting TAG 277 (SamplesPerPixel) to be 1, the producer indicates that there is a single sample per pixel.

[[r136]]
[caption=""]
.Requirement 136
====
(constrains TIFF<<35>> Section 19) A TIFF file storing tiled gridded elevation data SHALL have the 32-bit floating (FLOAT – 11) data type.
====

By setting TAG 339 (SampleFormat) to be 3, the producer indicates that the Sample Value is IEEE floating point as defined in Part 2 (TIFF Extensions) Section 19: Data Sample Format TIFF<<35>>. By setting TAG 258 (BitsPerSample) to be 32, the producer indicates that there are 32 bits per sample.

[[r137]]
[caption=""]
.Requirement 137
====
A TIFF file storing tiled gridded elevation data MAY use the LZW compression option as per TIFF<<35>> Section 13.
====

Client applications that support the TIFF encoding are expected to support this option.

[[r138]]
[caption=""]
.Requirement 138
====
(constrains TIFF<<35>> Section 2) A TIFF file storing tiled gridded elevation data SHALL NOT contain multiple images per TIFF file.
====

[[r139]]
[caption=""]
.Requirement 139
====
(constrains TIFF<<35>> Section 15) A TIFF file storing tiled gridded elevation data SHALL NOT contain internal tiles as per TIFF Section 15.
====

[[r139]]
[caption=""]
.Requirement 143
====
All pixels in an elevation tile SHALL be set with a valid component value. The mechanisms defined in this extension SHALL be used to indicate a missing value for a pixel.
====

[float]
==== Abstract Test Suite

[float]
===== Table Definitions

[float]
====== Coverage Ancillary
[cols="1,5a"]
|========================================
|*Test Case ID* |+/extensions/elevation/table_def/gpkg_2d_gridded_coverage_ancillary+
|*Test Purpose:* |Verify that the "gpkg_2d_gridded_coverage_ancillary" table has the proper definition.
|*Test Method:* |
. +PRAGMA table_info(gpkg_2d_gridded_coverage_ancillary)+
. Fail if table does not have all of the columns specified in Table 27
. Pass if logged pass and no fails
|*Reference* |Annex F.11 Req 120
|*Test Type* |Basic
|========================================

[float]
====== Tile Ancillary
[cols="1,5a"]
|========================================
|*Test Case ID* |+/extensions/elevation/table_def/gpkg_2d_gridded_tile_ancillary+
|*Test Purpose:* |Verify that the "gpkg_2d_gridded_tile_ancillary" table has the proper definition.
|*Test Method:* |
. +PRAGMA table_info(gpkg_2d_gridded_tile_ancillary)+
. Fail if table does not have all of the columns specified in Table 28
. Pass if logged pass and no fails
|*Reference* |Annex F.11 Req 121
|*Test Type* |Basic
|========================================

[float]
===== Table Values

[float]
====== Spatial Reference

[cols="1,5a"]
|========================================
|*Test Case ID* |+/extensions/elevation/table_val/gpkg_spatial_ref_sys/rows+
|*Test Purpose:* |Verify that the "gpkg_spatial_ref_sys" table has the required rows.
|*Test Method:* |
. +SELECT COUNT(*) FROM gpkg_spatial_ref_sys WHERE organization_coordsys_id = 4979 AND (organization = 'EPSG' OR organization = 'epsg')+
. Fail if count is zero
. Pass if logged pass and no fails
|*Reference* |Annex F.11 Req 122
|*Test Type* |Basic
|========================================

[cols="1,5a"]
|========================================
|*Test Case ID* |+/extensions/elevation/table_val/gpkg_spatial_ref_sys/refs+
|*Test Purpose:* |Verify that all elevation data uses an SRS that is defined in gpkg_spatial_ref_sys
|*Test Method:* |	
. +SELECT table_name FROM gpkg_contents WHERE data_type = '2d-gridded-coverage';+
. For each table_name
.. +SELECT COUNT(*) FROM gpkg_tile_matrix_set WHERE table_name = '{table_name}'+
.. Fail if count is not 1
. Pass if no fails
|*Reference:* |Annex F.11 Req 123
|*Test Type* |Capability
|========================================

[float]
====== Contents

[cols="1,5a"]
|========================================
|*Test Case ID* |+/extensions/elevation/table_val/gpkg_spatial_ref_sys+
|*Test Purpose:* |Verify that all elevation data uses an SRS that is defined in gpkg_spatial_ref_sys
|*Test Method:* |	
. +SELECT table_name FROM gpkg_contents WHERE data_type = '2d-gridded-coverage';+
. Not testable if result set is empty
. Manually inspect that all elevation data is accounted for in the result set
|*Reference:* |Annex F.11 Req 124
|*Test Type* |Capability
|========================================

[float]
====== Extensions

[cols="1,5a"]
|========================================
|*Test Case ID* |+/extensions/elevation/table_val/gpkg_extensions+
|*Test Purpose:* |Verify that all required rows are present in gpkg_extensions
|*Test Method:* |	
. +SELECT table_name, column_name, extension_name, definition, scope from gpkg_extensions";+
. Verify that the required rows in Table 30 for table_name gpkg_2d_gridded_coverage_ancillary and gpkg_2d_gridded_tile_ancillary are present.
. SELECT table_name FROM gpkg_contents WHERE data_type = '2d-gridded-coverage';
. For each table_name
.. SELECT column_name, definition, scope from gpkg_extensions WHERE extension_name = 'gpkg_elevation_tiles' AND table_name = '{table_name}'
.. Fail if no rows found
.. Fail if the results do not match the entry in Table 30 for a user defined table
. Pass if no fails 
|*Reference:* |Annex F.11 Req 125
|*Test Type* |Capability
|========================================

[float]
====== Coverage Ancillary

[cols="1,5a"]
|========================================
|*Test Case ID* |+/extensions/elevation/table_ref/gpkg_contents/gpkg_2d_gridded_coverage_ancillary+
|*Test Purpose:* |Verify that all required rows are present in gpkg_2d_gridded_coverage_ancillary
|*Test Method:* |	
. +SELECT table_name FROM gpkg_contents WHERE data_type = '2d-gridded-coverage';+
. For each table_name
.. SELECT COUNT(*) FROM gpkg_2d_gridded_coverage_ancillary WHERE tile_matrix_set_name =  '{table_name}'
.. Fail if count is not 1
. Pass if no fails 
|*Reference:* |Annex F.11 Req 126
|*Test Type* |Capability
|========================================

[cols="1,5a"]
|========================================
|*Test Case ID* |+/extensions/elevation/table_ref/gpkg_2d_gridded_coverage_ancillary/gpkg_tile_matrix_set+
|*Test Purpose:* |Verify that gpkg_2d_gridded_coverage_ancillary references gpkg_tile_matrix_set
|*Test Method:* |	
. +SELECT tile_matrix_set_name FROM 'gpkg_2d_gridded_coverage_ancillary';+
. For each tile_matrix_set_name
.. SELECT count(*) FROM gpkg_tile_matrix_set WHERE table_name = '{tile_matrix_set_name}'
.. Fail if count is not 1
. Pass if no fails 
|*Reference:* |Annex F.11 Req 127
|*Test Type* |Capability
|========================================

[cols="1,5a"]
|========================================
|*Test Case ID* |+/extensions/elevation/table_val/gpkg_2d_gridded_coverage_ancillary+
|*Test Purpose:* |Verify that gpkg_2d_gridded_coverage_ancillary contains valid column values
|*Test Method:* |	
. +SELECT datatype, scale, offset FROM 'gpkg_2d_gridded_coverage_ancillary' WHERE tile_matrix_set_name IN (SELECT table_name FROM gpkg_contents WHERE data_type = '2d-gridded-coverage');+
. For each result in 1
.. Fail if datatype is not "integer" or "float"
.. Fail if datatype is "float" and scale is not 1.0
.. Fail if datatype is "float" and offset is not 0.0
. Pass if no fails 
|*Reference:* |Annex F.11 Req 128
|*Test Type* |Capability
|========================================

[float]
====== Tile Ancillary

[cols="1,5a"]
|========================================
|*Test Case ID* |+/extensions/elevation/table_ref/tpudt/gpkg_2d_gridded_tile_ancillary+
|*Test Purpose:* |Verify that all required rows are present in gpkg_2d_gridded_tile_ancillary
|*Test Method:* |	
. +SELECT table_name FROM gpkg_contents WHERE data_type = '2d-gridded-coverage';+
. For each table_name
.. SELECT {table_name}.id as tid, gpkg_2d_gridded_tile_ancillary.tpudt_id as taid from elev_png LEFT OUTER JOIN gpkg_2d_gridded_tile_ancillary ON {table_name}.id = gpkg_2d_gridded_tile_ancillary.tpudt_id AND gpkg_2d_gridded_tile_ancillary.tpudt_name = '{table_name}'
.. For each row
... Fail if taid is null
. Pass if no fails 
|*Reference:* |Annex F.11 Req 129, 131
|*Test Type* |Capability
|========================================

[cols="1,5a"]
|========================================
|*Test Case ID* |+/extensions/elevation/table_val/gpkg_2d_gridded_tile_ancillary+
|*Test Purpose:* |Verify that all required rows in gpkg_2d_gridded_tile_ancillary have valid values
|*Test Method:* |	
. +SELECT tpudt_name, scale, offset FROM gpkg_2d_gridded_tile_ancillary;+
. For each row
.. PRAGMA table_info({tpudt_name})
.. Fail if tpudt_name is not a table or view
.. SELECT datatype from gpkg_2d_gridded_coverage_ancillary WHERE tile_matrix_set_name = '{tpudt_name}'
.. Fail if no rows found
.. Fail if datatype is "float" and scale is not 1.0
.. Fail if datatype is "float" and offset is not 0.0
. Pass if no fails 
|*Reference:* |Annex F.11 Req 130
|*Test Type* |Capability
|========================================

[float]
====== Tile Pyramid User Data Table

[cols="1,5a"]
|========================================
|*Test Case ID* |+/extensions/elevation/table_val/tpudt+
|*Test Purpose:* |Verify that all rows in tile pyramid user data tables have valid values
|*Test Method:* |	
. +SELECT table_name FROM gpkg_contents WHERE data_type = '2d-gridded-coverage';+
. For each table_name
.. SELECT t.datatype AS datatype, u.id AS id, u.tile_data AS tile_data FROM gpkg_2d_gridded_coverage_ancillary t, {table_name} u WHERE t.tile_matrix_set_name = 'table_name';
.. For each row
... If datatype is float, fail if tile_data is not a valid TIFF image as per requirements 134-139
... If datatype is integer, fail if tile_data is not a valid PNG image
. Pass if no fails 
|*Reference:* |Annex F.11 Req 132, 133, 134-139, 143
|*Test Type* |Capability
|========================================
