[[extension_tiles_webp]]
=== Tiles Encoding WebP

[float]
==== Introduction

This extension of clauses <<tile_enc_png>> and <<tile_enc_jpeg>> allows encoding of tile images in WebP format.

PNG and JPEG are the default MIME types for encoding images in tile pyramid user data tables.
This extension allows the use of `image/x-webp` as an additional encoding type.

[float]
==== Extension Author

GeoPackage SWG, author_name `gpkg`.

[float]
==== Extension Name or Template

`gpkg_webp`

[float]
==== Extension Type

Extension of Existing Requirement in clauses <<tile_enc_png>> and <<tile_enc_jpeg>>.

[float]
==== Applicability

This extension applies to any table listed in the `gpkg_contents` table with a data_type of `tiles`.

[float]
==== Scope

Read-write

[float]
==== Requirements

[float]
===== GeoPackage

[[r90]]
[caption=""]
.Requirement 90
====
GeoPackages with one or more rows in the `gpkg_extensions` table with an `extension_name` of "gpkg_webp" SHALL comply with this extension.
====

[[r91]]
[caption=""]
.Requirement 91
====
A GeoPackage that contains tile pyramid user data tables with `tile_data` columns that contain images in WebP format SHALL contain a `gpkg_extensions` table that contains row records with `table_name` values for each such table, `column_name` values of "tile_data", `extension_name` column values of "gpkg_webp", and `scope` column values of "read-write".
====

[[r92]]
[caption=""]
.Requirement 92
====
(extends http://www.geopackage.org/spec/#r36[GPKG-36] and http://www.geopackage.org/spec/#r37[GPKG-37]) A GeoPackage that contains a tile pyramid user data table that contains tile data MAY store tile_data in http://www.ietf.org/rfc/rfc2046.txt[MIME type] image/x-webp <<22>>.
The http://www.ietf.org/rfc/rfc2046.txt[MIME type] of values of the `tile_data` column in tile pyramid user data tables SHALL be `image/x-webp`.
====

[float]
===== GeoPackage SQLite Configuration

None

[float]
===== GeoPackage SQLite Extension

None

[float]
==== Abstract Test Suite

[float]
===== Extensions Name

[cols="1,5a"]
|========================================
|*Test Case ID* |+/extensions/tile_encoding_webp/data/webp_ext_name+
|*Test Purpose:* |Verify that the "gpkg_webp" extensions name is used to register WEBP tile encoding implementations.
|*Test Method:* |
. SELECT COUNT(*) FROM gpkg_extensions WHERE extension_name = 'gpkg_webp';
. Extension not in use if count is empty
|*Reference* |Annex F.7 Req 90
|*Test Type* |Basic
|========================================

[float]
===== Extensions Row

[cols="1,5a"]
|========================================
|*Test Case ID* |+/extensions/tile_encoding_webp/data/webp_ext_row+
|*Test Purpose:* |Verify that this extension is registered using proper rows in the `gpkg_extensions` table.
|*Test Method:* |	
. /opt/extension_mechanism/data/data_values_table_name will test whether the `table_name` values are valid.
. SELECT column_name, scope FROM gpkg_extensions where extension_name = 'gpkg_webp';
. For each row table_name from step 1
.. Fail if `column_name` is not "tile_data"
.. Fail if `scope` is not "read-write"
. Pass if no fails
|*Reference:* |Annex F.7 Req 91
|*Test Type* |Capability
|========================================

[float]
===== Extensions Mime Type

[cols="1,5a"]
|========================================
|*Test Case ID* |+/extensions/tiles_encoding_webp/data/mime_type_webp+
|*Test Purpose* |Verify that a tile matrix user data table that conforms to this extension contains a valid image type, including images of MIME type image/x-webp.
|*Test Method* |
. SELECT table_name FROM gpkg_extensions WHERE extension_name = 'gpkg_webp'
. For each table_name from step 1
.. Run test /opt/tiles/tiles_encoding/data/mime_type_jpeg step 2 but allow an extra MIME type (step 2c) of "image/x-webp"
. Pass if no fails
|*Reference* |Annex F.7 Req 92
|*Test Type* |Capability
|========================================
