[[extension_crs_wkt]]
=== WKT for Coordinate Reference Systems

[float]
==== Introduction

The OGC GeoPackage standard was adopted prior to the adoption of "OGC Well known text representation of Coordinate Reference Systems" <<34>>, in 13 August, 2014. As a result, the OGC GeoPackage standard references an older document <<32>> which has known ambiguities that are being encountered in the field. This extension establishes a new column to contain values that conform to the new standard.

[float]
==== Extension Author

GeoPackage SWG, author_name `gpkg`.

[float]
==== Extension Name or Template

`gpkg_crs_wkt`

[float]
==== Extension Type

Extension of Existing Requirement in clause <<spatial_ref_sys_data_table_definition>>.

[float]
==== Applicability

Applies to the `gpkg_spatial_ref_sys` table.

[float]
==== Scope

Read-write

[float]
==== Requirements
[float]
===== Table
[float]
====== Table Definition
[requirement]
The `gpkg_spatial_ref_sys` table in a GeoPackage SHALL have an additional column called `definition_12_163` as per <<gpkg_spatial_ref_sys_cols_crs_wkt>> and <<gpkg_spatial_ref_sys_crs__12_163wkt_sql>>.

[[gpkg_spatial_ref_sys_cols_crs_wkt]]
.Spatial Ref Sys Table Definition
[cols=",,,,",options="header",]
|=======================================================================
|Column Name |Column Type |Column Description |Null |Key
|`srs_name` |TEXT |Human readable name of this SRS |no |
|`srs_id` |INTEGER |Unique identifier for each Spatial Reference System within a GeoPackage |no |PK
|`organization` |TEXT |Case-insensitive name of the defining organization e.g. EPSG or epsg |no |
|`organization_coordsys_id` |INTEGER |Numeric ID of the Spatial Reference System assigned by the organization |no |
|`definition` |TEXT |Well-known Text <<32>> Representation of the Spatial Reference System |no |
|`description` |TEXT |Human readable description of this SRS |yes |
|`definition_12_163` |TEXT |Well-known Text <<34>> Representation of the Spatial Reference System |no |
|=======================================================================

[float]
====== Table Data Values
[requirement]
Values of the `definition_12_163` column SHALL be constructed per the WKT syntax in <<34>>.

[float]
==== Abstract Test Suite
[float]
===== Table Definition
*Table Definition*

[cols="1,5a"]
|========================================
|*Test Case ID* |+/extension_crs_wkt/table_def+
|*Test Purpose* |Verify that the gpkg_spatial_ref_sys table exists and has the correct definition. Extends `/base/core/gpkg_spatial_ref_sys/data/table_def`.
|*Test Method* |
. `SELECT sql FROM sqlite_master WHERE type = 'table' AND tbl_name = 'gpkg_spatial_ref_sys'`
. Fail if returns an empty result set
. Pass if column names and column definitions in the returned `CREATE TABLE statement` in the sql column value, including data type, nullability, and primary key constraints match all of those in the contents of Annex F.10 Table 47. Column order, check constraint and trigger definitions, and other column definitions in the returned sql are irrelevant.
. Fail otherwise.
|*Reference* |Annex F.10 Req 115
|*Test Type* |Basic
|========================================

[[spatial_ref_sys_data_values_default_xx]]
[float]
===== Table Data Values

[cols="1,5a"]
|========================================
|*Test Case ID* |+/extension_crs_wkt/data_values_default+
|*Test Purpose* |Verify that the gpkg_spatial_ref_sys table contains the required default contents. Replaces `/base/core/gpkg_spatial_ref_sys/data_values_default`.
|*Test Method* |
. `SELECT srs_id, organization, organization_coordsys_id, description_12_163 FROM gpkg_spatial_ref_sys WHERE srs_id = -1 returns -1 “NONE” -1 “undefined”, AND`
. `SELECT srs_id, organization, organization_coordsys_id, description_12_163 FROM gpkg_spatial_ref_sys WHERE srs_id = 0 returns 0 “NONE” 0 “undefined”, AND`
. `SELECT definition_12_163 FROM gpkg_spatial_ref_sys WHERE organization IN (“epsg”,”EPSG”) AND organization_coordsys_id 4326` returns GEODCRS["WGS 84",
  DATUM["World Geodetic System 1984",
    ELLIPSOID["WGS 84",6378137, 298.257223563, LENGTHUNIT["metre", 1.0]]],
  PRIMEM["Greenwich", 0.0, ANGLEUNIT["degree",0.0174532925199433]],
  CS[ellipsoidal, 2],
  AXIS["latitude", north, ORDER[1]],
  AXIS["longitude", east, ORDER[2]],
  ANGLEUNIT["degree", 0.0174532925199433],
  ID["EPSG", 4326]]
. Pass if tests 1-3 are met
. Fail otherwise
|*Reference* |Annex F.10 Req 117
|*Test Type* |Capability
|========================================

[float]
==== Table Definition SQL

[float]
===== gpkg_spatial_ref_sys

[[gpkg_spatial_ref_sys_crs_wkt_sql]]
.gpkg_spatial_ref_sys Table Definition SQL (CRS WKT Extension)
[cols=","]
|=============
|
|=============
[source,sql]
----
CREATE TABLE gpkg_spatial_ref_sys (
  srs_name TEXT NOT NULL,
  srs_id INTEGER NOT NULL PRIMARY KEY,
  organization TEXT NOT NULL,
  organization_coordsys_id INTEGER NOT NULL,
  definition  TEXT NOT NULL,
  description TEXT,
  definition_12_163 TEXT NOT NULL
);
----

