[[extension_geometry_types]]
=== GeoPackage Non-Linear Geometry Types

[float]
==== Introduction

This extension of clause <<sql_geometry_types>> defines additional geometry types.

Clause 2.1.4 of the GeoPackage Version 1 Encoding Standard specifies support for the Geometry, Point, LineString, Polygon, MultiPoint, MultiLineString, MultiPolygon, and GeomCollection geometry types in the GeoPackageBinary geometry encoding format specified in clause 2.1.3.
This extension specifies support for the additional CircularString, CompoundCurve, CurvePolygon, MultiCurve, MultiSurface, Curve, and Surface geometry types in the GeoPackage Binary geometry encoding format using the codes from <<geometry_types_extension>>.

[float]
==== Extension Author

GeoPackage SWG, author_name `gpkg`

[float]
==== Extension Name or Template

Extension names are constructed from the gpkg_geom_<gname> template where <gname> is the uppercase name of the extension geometry type from <<geometry_types_extension>>.

[float]
==== Extension Type

Extension of Existing Requirement in clause <<sql_geometry_types>>

[float]
==== Applicability

This extension applies to any column specified in the `gpkg_geometry_columns` table.

[float]
==== Scope

Read-write

[float]
==== Requirements

[float]
===== GeoPackage

[requirement]
A GeoPackage MAY store feature table geometries with the extended non-linear geometry types (CircularString, CompoundCurve, CurvePolygon, MultiCurve, MultiSurface, Curve, Surface) in <<geometry_types>>.

[requirement]
The GeoPackageBinary geometry encoding format specified in clause <<gpb_format>> SHALL be used to encode non-linear geometry types using the type codes in <<geometry_types>> table <<geometry_types_extension>>.

[requirement]
[[extension_geometry_types_extensions_name]]
An extension name to specify a feature geometry extension type SHALL be defined for the “gpkg” author name using the “gpkg_geom_<gname>” template where <gname> is the uppercase name of the extension geometry type from <<geometry_types>> used in a GeoPackage.

[requirement]
A GeoPackage that contains a gpkg_geometry_columns table or updateable view with row records that specify extension geometry_type_name column values SHALL contain a gpkg_extensions table that contains row records with table_name and column_name values from the gpkg_geometry_columns row records that identify extension type uses, and extension_name column values for each of those geometry types constructed per the previous requirement <<extension_geometry_types_extensions_name>>.

[float]
===== GeoPackage SQLite Configuration

None

[float]
===== GeoPackage SQLite Extension

[requirement]
SQL functions that operate on GeoPackageBinary geometries as specified in other extensions SHALL operate correctly on the non-linear geometries specified in this extension.

[float]
==== Abstract Test Suite

[float]
===== GeoPackage Extension Types

[cols="1,5a"]
|========================================
|*Test Case ID* |+/reg_ext/features/geometry_encoding/data/geopackage_extension_types/existing_sparse_data+
|*Test Purpose* |Verify that existing extended non-linear geometry types are stored in valid StandardGeoPackageBinary format encodings.
|*Test Method* |
. SELECT table_name FROM gpkg_geometry_columns
. Not testable if returns an empty result set
. SELECT table_name AS tn, column_name AS cn FROM gpkg_geometry_columns WHERE table_name IN (SELECT table_name FROM gpkg_contents WHERE data_type = ‘features’),
. Fail if returns an empty result set
. For each row from step 3
.. SELECT cn FROM tn;
.. For each row from step a, log fail if GeoPackageBinary “X” type flag is 1
.. For each row from step a, if bytes 2-5 of cn.wkb as uint32 in endianness of gc.wkb byte 1of cn from #1 are a geometry type value from Annex G Table 43, then
.. Log cn.header values, wkb endianness and geometry type
ii. If cn.wkb is not correctly encoded per ISO 13249-3 clause 5.1.46 then log fail
iii. If cn.flags.E is 1 - 4 and some cn.wkbx is outside of cn.envelope.minx,maxx then log fail
iv. If cn.flags.E is 1 - 4 and some gc.wkby is outside of cn.envelope.miny,maxy then log fail
.. If cn.flags.E is 2,4 and some gc.wkb.z is outside of cnenvelope.minz,maxz then log fail
vi. If cn.flags.E is 3,4 and some gc.wkb.m is outside of cn.envelope.minm,maxm then log fail
vii. If cn.flags.E is 5-7 then log fail
viii. Otherwise log pass
. Log pass if log contains pass and no fails
|*Reference* |Annex F.1 Req 65:
|*Test Type* |Capability
|========================================

[cols="1,5a"]
|========================================
|*Test Case ID* |+/reg_ext/features/geometry_encoding/data/geopackage_extension_types/all_types_test_data+
|*Test Purpose* |Verify that all extended non-linear geometry types and options are stored in valid GeoPackageBinary format encodings.
|*Test Method* |
. Open GeoPackage that has feature geometry values of geometry type in Annex G, for an assortment of srs_ids, for an assortment of coordinate values, without and with z and / or m values, in both big and little endian encodings:
. /reg_ext/features/geometry_encoding/data/extension_types_existing_sparse_data
. Pass if log contains pass record for big and little endian GP headers containing big and little endian WKBs for 0-1 envelope contents indicator codes for every geometry type value from Annex G without and with z and/or m values.
. Fail otherwise
|*Reference* |Annex F.1 Req 66:
|*Test Type* |Capability
|========================================

[float]
===== Extensions Name

[cols="1,5a"]
|========================================
|*Test Case ID* |+/reg_ext/features/geometry_encoding/data/geopackage_extension_types/extension_name+
|*Test Purpose* |Verify that an extension name in the form gpkg_geom_<gname> is defined for each <gname> extension geometry type from Annex G used in a GeoPackage.
|*Test Method* |
. SELECT table_name, column_name FROM gpkg_geometry_columns WHERE table_name IN (SELECT table_name FROM gpkg_contents WHERE data_type  == ‘features'))
. Not testable if result set is empty
. For each row result set table_name, column_name from step 3
.. SELECT result_set_column_name FROM result_set_table_name
.. For each geometry column value from step a
... If the first two bytes of each geometry column value are “GP”, then
.... /opt/extension_mechanism/extensions/data/table_def
.... Fail if failed
.... SELECT ST_GeometryType(geometry column value) AS <gtype>;
.... SELECT extension_name FROM gpkg_extensions WERE table_name = result_set_table_name AND column_name = result_set_column_name AND extension_name = \'gpkg_geom_' \|\| <gtype>
..... Fail if result set is empty
..... Log pass otherwise
. Pass if logged pass and no fails
|*Reference* |Annex F.1 Req 67:
|*Test Type* |Basic
|========================================

[float]
===== Extensions Row

[cols="1,5a"]
|========================================
|*Test Case ID* |+/reg_ext/features/geometry_encoding/data/geopackage_extension_types/extension_row+
|*Test Purpose* |Verify that the gpkg_extensions table contains a row with an extension_name in the form gpkg_geom_<gname> for each table_name and column_name in the gpkg_geometry_columns table with a <gname> geometry_type_name.
|*Test Method* |
 /reg_ext/features/geometry_encoding/data/extension_name
|*Reference* |Annex F.1 Req 68:
|*Test Type* |Capability
|========================================

