[[extension_crs_wkt]]
=== WKT for Coordinate Reference Systems

[float]
==== Introduction

The OGC GeoPackage standard was adopted prior to the adoption of "OGC Well known text representation of Coordinate Reference Systems" <<34>>, in 13 August, 2014. As a result, the OGC GeoPackage standard references an older document <<32>> which has known ambiguities that are being encountered in the field. This extension establishes a new column to contain values that conform to the new standard.

[float]
==== Extension Author

GeoPackage SWG, author_name `gpkg`.

[float]
==== Extension Name or Template

`gpkg_crs_wkt`

[float]
==== Extension Type

Extension of Existing Requirement in clause <<spatial_ref_sys_data_table_definition>>.

[float]
==== Applicability

Applies to the `gpkg_spatial_ref_sys` table.

[float]
==== Scope

Read-write

[float]
==== Requirements
[float]
===== Table
[float]
====== Table Definition
[[r115]]
[caption=""]
.Requirement 115
====
For GeoPackages conforming to this extension, the `gpkg_spatial_ref_sys` table SHALL have an additional column called `definition_12_063` as per <<gpkg_spatial_ref_sys_cols_crs_wkt>> and <<gpkg_spatial_ref_sys_crs_wkt_sql>>.
====

[[gpkg_spatial_ref_sys_cols_crs_wkt]]
.Spatial Ref Sys Table Definition
[cols=",,,,,",options="header",]
|=======================================================================
|Column Name |Column Type |Column Description |Not Null |Default|Key
|`srs_name` |TEXT |Human readable name of this SRS |yes ||
|`srs_id` |INTEGER |Unique identifier for each Spatial Reference System within a GeoPackage |yes ||PK
|`organization` |TEXT |Case-insensitive name of the defining organization e.g. EPSG or epsg |yes ||
|`organization_coordsys_id` |INTEGER |Numeric ID of the Spatial Reference System assigned by the organization |yes ||
|`definition` |TEXT |Well-known Text <<32>> Representation of the Spatial Reference System |yes |'undefined'| 
|`description` |TEXT |Human readable description of this SRS |no ||
|`definition_12_063` |TEXT |Well-known Text <<34>> Representation of the Spatial Reference System |yes |'undefined'|
|=======================================================================

[float]
====== Table Data Values
[[r116]]
[caption=""]
.Requirement 116
====
Values of the `definition_12_063` column SHALL be constructed per the WKT syntax in <<34>>.
====

[[r117]]
[caption=""]
.Requirement 117
====
At least one definition column SHALL be defined with a valid definition unless the value of the `srs_id` column is `0` or `-1`. Both columns SHOULD be defined. If it is not possible to produce a valid <<32>> definition then the value of the `definition` column MAY be `undefined`. If it is not possible to produce a valid <<34>> definition then the value of the `definition_12_063` column MAY be `undefined`.
====

If, for a particular row, both the `definition` and `definition_12_063` columns are populated, the value in the `definition_12_063` column takes priority.

[float]
==== Abstract Test Suite
[float]
===== Table Definition
*Table Definition*

[cols="1,5a"]
|========================================
|*Test Case ID* |+/extension_crs_wkt/table_def+
|*Test Purpose* |Verify that the gpkg_spatial_ref_sys table exists and has the correct definition. Extends `/base/core/gpkg_spatial_ref_sys/data/table_def`.
|*Test Method* |
. `SELECT sql FROM sqlite_master WHERE type = 'table' AND tbl_name = 'gpkg_spatial_ref_sys'`
. Fail if returns an empty result set
. Pass if column names and column definitions in the returned `CREATE TABLE statement` in the sql column value, including data type, nullability, and primary key constraints match all of those in the contents of Annex F.10 Table 47. Column order, check constraint and trigger definitions, and other column definitions in the returned sql are irrelevant.
. Fail otherwise.
|*Reference* |Annex F.10 Req 115
|*Test Type* |Basic
|========================================

[float]
===== Table Data Values

[cols="1,5a"]
|========================================
|*Test Case ID* |+/extension_crs_wkt/data_values_default+
|*Test Purpose* |Verify that the gpkg_spatial_ref_sys table contains the required default contents. Extends `/base/core/gpkg_spatial_ref_sys/data_values_default`.
|*Test Method* |
. `SELECT organization, organization_coordsys_id, definition, definition_12_063 FROM gpkg_spatial_ref_sys WHERE srs_id = -1`
.. Confirm that this returns "NONE" -1 "undefined" "undefined"
. `SELECT srs_id, organization, organization_coordsys_id, definition, definition_12_063 FROM gpkg_spatial_ref_sys WHERE srs_id = 0`
.. Confirm that this returns "NONE" 0 "undefined" "undefined"
. `SELECT definition FROM gpkg_spatial_ref_sys WHERE organization IN ("epsg","EPSG") AND organization_coordsys_id 4326` 
.. Confirm that this is a valid CRS
. `SELECT definition_12_063 FROM gpkg_spatial_ref_sys WHERE organization IN ("epsg","EPSG") AND organization_coordsys_id 4326`
.. Confirm that this is a valid 12-063 CRS
. Pass if tests 1-4 are met
. Fail otherwise
|*Reference* |Annex F.10 Req 116
|*Test Type* |Capability
|========================================

[cols="1,5a"]
|========================================
|*Test Case ID* |+/extension_crs_wkt/data_values_undefined+
|*Test Purpose* |Verify that the gpkg_spatial_ref_sys table contains the required default contents. Replaces `/base/core/gpkg_spatial_ref_sys/data_values_default`.
|*Test Method* |
. `SELECT definition, definition_12_063 FROM gpkg_spatial_ref_sys WHERE srs_id NOT IN (0, -1)`
. Fail if both definition values are `undefined`
. Pass otherwise
|*Reference* |Annex F.10 Req 117
|*Test Type* |Capability
|========================================

[float]
==== Table Definition SQL

[float]
===== gpkg_spatial_ref_sys

[[gpkg_spatial_ref_sys_crs_wkt_sql]]
.gpkg_spatial_ref_sys Table Definition SQL (CRS WKT Extension)
[cols=","]
[source,sql]
----
CREATE TABLE gpkg_spatial_ref_sys (
  srs_name TEXT NOT NULL,
  srs_id INTEGER NOT NULL PRIMARY KEY,
  organization TEXT NOT NULL,
  organization_coordsys_id INTEGER NOT NULL,
  definition  TEXT NOT NULL DEFAULT 'undefined',
  description TEXT,
  definition_12_063 TEXT NOT NULL DEFAULT 'undefined'
);
----
