[[extension_geometry_encoding]]
=== User Defined Geometry Types Extension of GeoPackageBinary Geometry Encoding

[float]
==== Introduction

This extension of clauses <<gpb_format>>, <<sql_geometry_types>> and <<extension_geometry_types>> enables encoding of additional user-defined geometry types in ExtendedGeoPackageBinary format in an Extended GeoPackage.

This extension specifies a standard way to implement user defined extensions of the GeoPackageBinary geometry encoding format to encode geometry types not specified in clauses <<sql_geometry_types>> and <<extension_geometry_types>> and listed in <<geometry_types>>.
It is intended to be a bridge to enable use of geometry types like EllipiticalCurve in Extended GeoPackages until standard encodings of such types are developed and published for the Well Known Binary (WKB) format.

[float]
==== Extension Author

Name of implementer, author_name NOT `gpkg`.

[float]
==== Extension Name or Template

Extension names are constructed from the <author_name>_geom_<gname> template where <gname> is the uppercase name of an extension geometry type NOT in <<geometry_types>>.

[float]
==== Extension Type

Extension of Existing Requirement in clauses <<gpb_format>>, <<sql_geometry_types>> and <<extension+_geometry_types>>.

[float]
==== Applicability

This extension applies to any column specified in the gpkg_geometry_columns table.

[float]
==== Scope

Read-write

[float]
==== Requirements

This extension specifies use of an ExtendedGeoPackageBinary encoding format for geometry types not listed in <<geometry_types>>, and use of the extension name in uppercase for the `geometry_type_name` column value in the `gpkg_geometry_columns` table.

[float]
===== GeoPackage

[requirement]
The ExtendedGeoPackageBinary format SHALL be used to encode geometry types other than those specified in clauses <<sql_geometry_types>> and <<extension_geometry_types>> and listed in <<geometry_types>>.
One of the reserved bits in the GeoPackageBinary header is used to indicate the presence of the ExtendedGeopackageBinary encoding format.
In the extension case a four byte sequence follows the GPB header to disambiguate various extensions.
This extension_code SHOULD identify the implementer of the extension and/or the particular geometry type extension, and SHOULD be unique.
The actual extension geometry body is not specified, but SHALL be described in the extension document.

----
ExtendedGeoPackageBinary {
  GeoPackageBinaryHeader header; <1>
  byte[4] extension_code;        <2>
  byte[] extension_specific;     <3>
}
----

<1> The X bit in the header flags field must be set to 1.
<2> To indicate different extensions or vendors. 0x47504B47 (GPKG in ASCII) is reserved.
<3> Extension specific contents

[[user_defined_geometry_ext_name_req]]
[requirement]
An extension name to specify a feature geometry extension type encoded in the ExtendedGeoPackageBinary format SHALL be defined for an author name that is NOT “gpkg” using the “<author_name>_geom_<gname> template where <gname> is the uppercase name of an extension geometry type NOT listed in <<geometry_types>> used in a GeoPackage.

[requirement]
An Extended GeoPackage that contains a gpkg_geometry_columns table or updateable view with row records that specify extension geometry_type_name column values other than those specified in clauses <<sql_geometry_types>> and <<extenstion_geometry_types>> and listed in <<geometry_types>> SHALL contain a gpkg_extensions table that contains row records with table_name and column_name values from the gpkg_geometry_columns row records that identify extension type uses, and extension_name column values for each of those geometry type constructed per clause 3.1.2.1.2.

[requirement]
The `geometry_type_name` value in a `gpkg_geometry_columns` row SHALL be the <<user_defined_geometry_ext_name_req>> extension name in uppercase.


[float]
===== GeoPackage SQLite Configuration

None

[float]
===== GeoPackage SQLite Extension

[requirement]
SQL functions that operate on GeoPackageBinary geometries as specified in other extensions SHALL operate correctly on user-defined geometry types encoded in the ExtendedGeopackageBinary format as specified in this extension.

[float]
==== Abstract Test Suite

[float]
===== Extensions Encoding

[cols="1,5a"]
|========================================
|*Test Case ID* |+/reg_ext/features/geometry_encoding/data/user_defined-geometry_types/existing_sparse_data+
|*Test Purpose* |Verify that existing extended geometry types not listed in Annex G are stored in valid ExtendedGeoPackageBinary format encodings.
|*Test Method* |
. SELECT table_name FROM gpkg_geometry_columns
. Not testable if returns an empty result set
. SELECT table_name AS tn, column_name AS cn FROM gpkg_geometry_columns WHERE geometry_type_name NOT IN (all geometry types listed in Annex G) AND table_name IN (SELECT table_name FROM gpkg_contents WHERE data_type = ‘features’),
. Fail if returns an empty result set
. For each row from step 3
.. SELECT cn FROM tn;
.. For each row from step a,
... log fail if GeoPackageBinary “X” type flag is 0
... Otherwise log pass
. Log pass if log contains pass and no fails
|*Reference* |Annex F.2 Req 70
|*Test Type* |Capability
|========================================

[float]
===== Extensions Name

[cols="1,5a"]
|========================================
|*Test Case ID* |+/reg_ext/features/geometry_encoding/data/user_defined_geometry_types/extension_name+
|*Test Purpose* |Verify that an extension name in the form <author>_geom_<gname> is defined for each extended geometry type not listed in Annex G used in a GeoPackage.
|*Test Method* |
. SELECT table_name, column_name FROM gpkg_geometry_columns WHERE table_name IN (SELECT table_name FROM gpkg_contents WHERE data_type  == \'features'))
. Not testable if result set is empty
. For each row result set table_name, column_name from step 3
.. SELECT result_set_column_name FROM result_set_table_name
.. For each geometry column value from step a
... If the first two bytes of each geometry column value are “GP”, then
.... /opt/extension_mechanism/extensions/data/table_def
.... Fail if failed
.... SELECT ST_GeometryType(geometry column value) AS <gtype>;
.... SELECT extension_name FROM gpkg_extensions WERE table_name = result_set_table_name AND column_name = result_set_column_name AND extension_name NOT LIKE ‘gpkg_%’ and extension_name  LIKE \'%_geom_' \|\| <gtype>
..... Fail if result set is empty
..... Log pass otherwise
. Pass if logged pass and no fails
|*Reference* |Annex F.2 Req 71
|*Test Type* |Basic
|========================================

[float]
===== Extensions Row

[cols="1,5a"]
|========================================
|*Test Case ID* |+/reg_ext/features/geometry_encoding/data/user_defined_geometry_types/extension_row+
|*Test Purpose* |Verify that the gpkg_extensions table contains a row with an extension_name in the form <author>_geom_<gname> for each table_name and column_name in the gpkg_geometry_columns table with a <gname> geometry_type_name.
|*Test Method* |
 Do test /reg_ext/features/geometry_encoding/data/extension_encoding/extension_name
|*Reference* |Annex F.2 Req 72
|*Test Type* |Capability
|========================================

[float]
===== Geometry Columns Row

[cols="1,5a"]
|========================================
|*Test Case ID* |+/reg_ext/features/geometry_encoding/data/user_defined_geometry_types/geometry_columns_row+
|*Test Purpose* |Verify that the gpkg_geometry_columns table contains a row with a geometry_type_name  in the form <author>_geom_<gname> for each feature table that contains user-defined geometry types specified in the gpkg_extensions table.
|*Test Method* |
. SELECT extension_name FROM gpkg_extensions WHERE extension_name LIKE ‘%_geom_%’ AND extension_name NOT LIKE ‘gpkg_geom_%’
. FOR EACH extension_name from #1
.. SELECT * FROM gpkg_geometry_columns WHERE geometry_type_name = extension_name
.. Fail if returns an empty result set
. Pass if no fails.

|*Reference* |Annex F.2 Req 73
|*Test Type* |Capability
|========================================

