[[extension_geometry_types]]
=== GeoPackage Non-Linear Geometry Types

[float]
==== Introduction

This extension of clause <<sql_geometry_types>> defines additional geometry types.

Clause 2.1.4 of the GeoPackage Version 1 Encoding Standard specifies support for the Geometry, Point, LineString, Polygon, MultiPoint, MultiLineString, MultiPolygon, and GeometryCollection geometry types in the GeoPackageBinary geometry encoding format specified in clause 2.1.3.
This extension specifies support for the additional CircularString, CompoundCurve, CurvePolygon, MultiCurve, MultiSurface, Curve, and Surface geometry types in the GeoPackage Binary geometry encoding format using the codes from <<geometry_types_extension>>.

[float]
==== Extension Author

GeoPackage SWG, author_name `gpkg`

[float]
==== Extension Name or Template

Extension names are constructed from the gpkg_geom_<gname> template where <gname> is the uppercase name of the extension geometry type from <<geometry_types_extension>>.

[float]
==== Extension Type

Extension of Existing Requirement in clause <<sql_geometry_types>>

[float]
==== Applicability

This extension applies to any column specified in the `gpkg_geometry_columns` table.

[float]
==== Scope

Read-write

[float]
==== Requirements

[float]
===== GeoPackage

[[r65]]
[caption=""]
.Requirement 65
====
(extends http://www.geopackage.org/spec/#r25[GPKG-25]) The `geometry_type_name` value in a `gpkg_geometry_columns` row MAY be one of the uppercase extended non-linear geometry type names specified in <<geometry_types>>.
====

[[r66]]
[caption=""]
.Requirement 66
====
The GeoPackageBinary geometry encoding format specified in clause <<gpb_format>> SHALL be used to encode non-linear geometry types using the type codes in <<geometry_types>> table <<geometry_types_extension>>.
====

[[r67]]
[caption=""]
.Requirement 67
====
[[extension_geometry_types_extensions_name]]
An extension name to specify a feature geometry extension type SHALL be defined for the "gpkg" author name using the "gpkg_geom_<gname>" template where <gname> is the uppercase name of the extension geometry type from <<geometry_types>> used in a GeoPackage.
====

[[r68]]
[caption=""]
.Requirement 68
====
A GeoPackage that contains a `gpkg_geometry_columns` table or view with row records that specify extension `geometry_type_name` column values SHALL contain a `gpkg_extensions` table that contains row records with `table_name` and `column_name` values from the `gpkg_geometry_columns` row records that identify extension type uses, and `extension_name` column values for each of those geometry types constructed per the previous requirement <<extension_geometry_types_extensions_name>>.
====

[float]
===== GeoPackage SQLite Configuration

None

[float]
===== GeoPackage SQLite Extension

[[r69]]
[caption=""]
.Requirement 69
====
[line-through]#SQL functions that operate on GeoPackageBinary geometries as specified in other extensions SHALL operate correctly on the non-linear geometries specified in this extension#.
====

[float]
==== Abstract Test Suite

[float]
===== GeoPackage Extension Types

[cols="1,5a"]
|========================================
|*Test Case ID* |+/extensions/geometry_types/data_values_geometry_type_name+
|*Test Purpose* |Verify that only allowed geometry types (including extended non-linear geometry types) are in use.
|*Test Method* |
. Run test /opt/features/geometry_columns/data/data_values_geometry_type_name, but the values in 3a may also include the values from Table 28 in Annex G.
|*Reference* |Annex F.1 Req 65:
|*Test Type* |Capability
|========================================

[cols="1,5a"]
|========================================
|*Test Case ID* |+/extensions/geometry_types/all_types_test_data+
|*Test Purpose* |Verify that geometries non-linear geometry types are stored in valid GeoPackageBinary format encodings.
|*Test Method* |
. SELECT table_name FROM gpkg_geometry_columns
. Not testable if returns an empty result set
. SELECT table_name AS tn, column_name AS cn FROM gpkg_geometry_columns WHERE table_name IN (SELECT table_name FROM gpkg_contents WHERE data_type = 'features'),
. Fail if returns an empty result set
. For each row from step 3
.. SELECT cn FROM tn;
.. For each row from step a, log fail if GeoPackageBinary "X" type flag is 1
.. For each row from step a, if bytes 2-5 of cn.wkb as uint32 in endianness of gc.wkb byte 1of cn from #1 are a geometry type value from Annex G Table 28, then
.. Log cn.header values, wkb endianness and geometry type
ii. If cn.wkb is not correctly encoded per ISO 13249-3 clause 5.1.46 then log fail
iii. If cn.flags.E is 1 - 4 and some cn.wkbx is outside of cn.envelope.minx,maxx then log fail
iv. If cn.flags.E is 1 - 4 and some gc.wkby is outside of cn.envelope.miny,maxy then log fail
.. If cn.flags.E is 2,4 and some gc.wkb.z is outside of cnenvelope.minz,maxz then log fail
vi. If cn.flags.E is 3,4 and some gc.wkb.m is outside of cn.envelope.minm,maxm then log fail
vii. If cn.flags.E is 5-7 then log fail
viii. Otherwise log pass
. Log pass if log contains pass and no fails

|*Reference* |Annex F.1 Req 66:
|*Test Type* |Capability
|========================================

[float]
===== Extensions Name

[cols="1,5a"]
|========================================
|*Test Case ID* |+/extensions/geometry_types/extension_name+
|*Test Purpose* |Verify that an extension name in the form gpkg_geom_<gname> is defined for each <gname> extension geometry type from Annex G used in a GeoPackage.
|*Test Method* |
. SELECT table_name, column_name FROM gpkg_geometry_columns WHERE table_name IN (SELECT table_name FROM gpkg_contents WHERE data_type  == 'features'))
. Not testable if result set is empty
. For each row result set table_name, column_name from step 3
.. SELECT result_set_column_name FROM result_set_table_name
.. For each geometry column value from step a
... If the first two bytes of each geometry column value are "GP", then
.... /opt/extension_mechanism/data/table_def
.... Fail if failed
.... SELECT ST_GeometryType(geometry column value) AS <gtype>;
.... SELECT extension_name FROM gpkg_extensions WERE table_name = result_set_table_name AND column_name = result_set_column_name AND extension_name = \'gpkg_geom_' \|\| <gtype>
..... Fail if result set is empty
..... Log pass otherwise
. Pass if logged pass and no fails
|*Reference* |Annex F.1 Req 67:
|*Test Type* |Basic
|========================================

[float]
===== Extensions Row

[cols="1,5a"]
|========================================
|*Test Case ID* |+/extensions/geometry_types/extension_row+
|*Test Purpose* |Verify that the gpkg_extensions table contains a row with an extension_name in the form gpkg_geom_<gname> for each table_name and column_name in the gpkg_geometry_columns table with a <gname> geometry_type_name.
|*Test Method* |
. SELECT table_name, column_name, geometry_type_name FROM gpkg_geometry_columns
. Not testable if no results
. For each result
.. If geometry_type_name is an extended geometry type
... SELECT extension_name FROM gpkg_extensions WHERE table_name = '{table_name}' AND column_name = '{column_name}"
... Fail if result set does not contain a row with an extension_name of gpkg_geom_{geometry_type_name}
. Pass if no fails
|*Reference* |Annex F.1 Req 68:
|*Test Type* |Capability
|========================================

