[[extension_geometry_type_triggers]]
=== Geometry Type Triggers 

[float]
==== Introduction

This extension adds a new geometry type triggers capability for columns with geometries encoded per clause <<gpb_format>> and <<extension_geometry_encoding>>.

Geometry type triggers prevent the storage of geometries of types that are not assignable from the geometry types specified in the gpkg_geometry_columns table in the geometry columns of the specified tables.

[float]
==== Extension Author

GeoPackage SWG, author_name `gpkg`.

[float]
==== Extension Name or Template

`gpkg_geometry_type_trigger`

[float]
==== Extension Type

New Requirement dependent on clauses <<gpb_format>> and <<extension_geometry_encoding>>.

[float]
==== Applicability

This extension applies to any column specified in the gpkg_geometry_columns table.

[float]
==== Scope

Write-only

[float]
==== Requirements

[float]
===== GeoPackage

[requirement]
The “gpkg_geometry_type_trigger” extension name SHALL be used as a gpkg_extensions table extension name column value to specify implementation of geometry type triggers.

[requirement]
A GeoPackage that implements geometry type triggers on geometry columns SHALL contain a gpkg_extensions table that contains a row for each such geometry column with extension_name “gpkg_geometry_type_trigger”, table_name of the feature table with a geometry column, and column_name of the geometry column.

[requirement]
A GeoPackage SHALL include the SQL insert and update triggers specified in <<extension_geometry_type_triggers>> on every geometry column to enforce the geometry type values specified for those columns in the gpkg_geometry_columns table.

The <t> and <c> template parameters in the geometry type trigger definition SQL template in the table below are to be replaced with the names of the feature table and geometry column being inserted or updated.

[source,sql]
----
CREATE TRIGGER fgti_<t>_<c> BEFORE INSERT ON '<t>' FOR EACH ROW
BEGIN
  SELECT RAISE (ABORT, 'insert on <t> violates constraint: ST_GeometryType(<c>) is not assignable from gpkg_geometry_columns.geometry_type_name value')
  WHERE (SELECT geometry_type_name FROM gpkg_geometry_columns
         WHERE Lower(table_name) = Lower('<t>')
	         AND Lower(column_name) = Lower('<c>')
	         AND gpkg_IsAssignable(geometry_type_name, ST_GeometryType(NEW.<c>)) = 0);
END

CREATE TRIGGER fgtu_<t>_<c> BEFORE UPDATE OF '<c>' ON '<t>' FOR EACH ROW
BEGIN
  SELECT RAISE (ABORT, 'update of <c> on <t> violates constraint: ST_GeometryType(<c>) is not assignable from gpkg_geometry_columns.geometry_type_name value')
  WHERE (SELECT geometry_type_name FROM gpkg_geometry_columns
         WHERE Lower(table_name) = Lower('<t>')
	         AND Lower(column_name) = Lower('<c>')
	         AND gpkg_IsAssignable(geometry_type_name, ST_GeometryType(NEW.<c>)) = 0);
END
----

[float]
===== GeoPackage SQLite Configuration

None

[float]
===== GeoPackage SQLite Extension

Definition of SQL functions

[cols=",,,",options="header"]
|======
|SQL Function |Description |Use
|ST_GeometryType(geom. Geometry) : TEXT |Returns the WKB geometry type name of a Geometry |Check that the geometry type matches what’s specified in gpkg_geometry_columns.geometry_type_name
|GPKG_IsAssignable(expected_type_name TEXT, actual_type_name TEXT): INTEGER |Returns 1 if a value of type expected_type_name is the same or a super type of type actual_type_name. Returns 0 otherwise. |Determine if the expected geometry type is the same as or a super type of the actual geometry type.
|======

[requirement]
The SQL functions on geometries in this SQLite Extension SHALL operate correctly on extended geometry types specified by <<extension_geometry_encoding>> and/or <<extension_geometry_types>> when those extensions are also implemented.

[float]
==== Abstract Test Suite

[float]
===== Implementation

[cols="1,5a"]
|========================================
|*Test Case ID* |+/reg_ext/features/geometry_type_triggers/implementation+
|*Test Purpose* |Verify that user feature data table geometry type triggers are implemented correctly.
|*Test Method* |
. SELECT table_name, column_name FROM gpkg_geometry_columns WHERE table_name IN (SELECT table_name FROM gpkg_contents WHERE data_type  == ‘features'))
. Not testable if returns an empty result set
. For each row table_name, column_name from step 1
.. SELECT sql FROM sqlite_master WHERE type = ‘trigger’ AND tbl_name = ‘fgti_’ \|\| result_set_table_name \|\| ‘_’ \|\| result_set_column_name
.. Not testable if returns an empty result set
.. Fail if sql != result of populating the first trigger template in Annex M with <t> as result_set_table_name and <c> as result_set_column_name
.. SELECT sql FROM sqlite_master WHERE type = ‘trigger’ AND tbl_name = ‘fgtu_’ \|\| result_set_table_name \|\| ‘_’ \|\| result_set_column_name
.. Fail if sql != result of populating the second trigger template in Annex M with <t> as result_set_table_name and <c> as result_set_column_name
.. Log pass otherwise
. Pass if logged pass and no fails
|*Reference* |Clause 3.1.4.1.1 Req 95:
|*Test Type* |Capability
|========================================

[cols="1,5a"]
|========================================
|*Test Case ID* |+/reg_ext/features/geometry_type_triggers/implementation/sql_functions+
|*Test Purpose* |Verify the correct implementation of sql functions used in geometry type triggers on feature table geometry columns.
|*Test Method* |
. Open Geometry Test Data Set GeoPackage with GeoPackage SQLite Extension
. For each Geometry Test Data Set <gtype_test> data table row for each assignable (gtype, atype) and non-assignable (ntype, atype) combination of geometry type in Annex E, for an assortment of srs_ids, for an assortment of coordinate values, without and with z and / or m values, in both big and little endian encodings:
.. SELECT ‘Fail’ FROM <gtype_test> WHERE GPKG_IsAssignable(gtype, atype) =0
.. SELECT ‘Fail’ FROM <gtype_test> WHERE GPKG_IsAssignable(ntype, atype) = 1
.. SELECT ‘Fail’ FROM <gtype_test> WHERE ST_GeometryType(geom) != atype
. Pass if no ‘Fail’ selected from step 2
|*Reference* |Clause 3.1.4.1.1 Req 95:
|*Test Type* |Capability
|========================================

[float]
===== Extensions Name

[cols="1,5a"]
|========================================
|*Test Case ID* |+/reg_ext/features/geometry_type_triggers/extension_name+
|*Test Purpose* |Verify that the “gpkg_geometry_type_trigger” extension name is used to register geometry type triggers.
|*Test Method* |
. SELECT table_name, column_name FROM gpkg_geometry_columns WHERE table_name IN (SELECT table_name FROM gpkg_contents WHERE data_type  == ‘features'))
. Not testable if result set is empty
. For each row table_name, column_name from step 1
.. SELECT sql FROM sqlite_master WHERE type = ‘trigger’ AND tbl_name = ‘fgti_’ \|\| result_set_table_name \|\| ‘_’ \|\| result_set_column_name
.. Not testable if result set is empty
.. /opt/extension_mechanism/extensions/data/table_def
.. Fail if failed
.. SELECT extension_name from gpkg_extensions WHERE table_name = result_set_table_name AND column_name = result_set_column_name
.. Log pass if result is “gpkg_geometry_type_trigger”
.. Fail otherwise
. Pass if logged pass and no fails
|*Reference* |Clause 3.1.4.1.2 Req 96:
|*Test Type* |Basic
|========================================

[float]
===== Extensions Row

[cols="1,5a"]
|========================================
|*Test Case ID* |+/reg_ext/features/geometry_type_triggers/extension_row+
|*Test Purpose* |Verify that geometry type triggers are registered using the “gpkg_geometry_type_trigger” extension name.
|*Test Method* |
 Do test /reg_ext/features/geometry_type_triggers/extension_name
|*Reference* |Clause 3.1.4.1.3 Req 97:
|*Test Type* |Capability
|========================================
