[[extension_template]]
[appendix]
== GeoPackage Extension Template (Normative)

[float]
=== Extension Title

Title of the Extension

[float]
=== Introduction

Description of extension

[float]
=== Extension Author

Author of extension, author_name.

[float]
=== Extension Name or Template

Name of the extension or definition of the template to create the name of extensions that should be used in gpkg_extensions

[float]
=== Extension Type

"Extension of Existing Requirement in Clause(s) XXX" or "New Requirement Dependent on Clause(s) YYY"

[float]
=== Applicability

Tables and/or columns on which this extension may be applied

[float]
=== Scope

Read-write or write-only with clarification if necessary

[float]
=== Requirements

Definition of extension and interdependencies with other extensions if any.

[float]
==== GeoPackage

Definition of extension data or MIME type(s)

Definition of extension tables or table templates

Definition of triggers or trigger templates

[float]
==== GeoPackage SQLite Configuration

Definition of SQLite configuration settings

[cols=",,,",options="header"]
|======
|Setting compile or runtime |Option |Shall / Not (Value) | Discussion
| | | |
|======

[float]
==== GeoPackage SQLite Extension

Definition of SQL functions

[cols=",,,",options="header"]
|======
|SQL Function |Description |Use
|foo(bar, baz) : datatype |Returns r when w |
|======
