[[extension_geometry_srsid_triggers]]
=== Geometry SRS ID Triggers 

[float]
==== Introduction

This extension adds a new srs_id triggers capability for columns with geometries encoded per clause <<gpb_format>> and <<extension_geometry_encoding>>.

Geometry SRS_ID triggers prevent the storage of geometries with spatial reference system identifiers that are not specified in the `gpkg_geometry_columns` table in the geometry columns of the specified tables.

[float]
==== Extension Author

GeoPackage SWG, author_name `gpkg`.

[float]
==== Extension Name or Template

`gpkg_srs_id_trigger`

[float]
==== Extension Type

New Requirement dependent on clauses <<gpb_format>> and <<extension_geometry_encoding>>.

[float]
==== Applicability

This extension applies to any column specified in the gpkg_geometry_columns table.

[float]
==== Scope

Write-only

[float]
==== Requirements

[float]
===== GeoPackage

[requirement]
The “gpkg_srs_id_trigger” extension name SHALL be used as a gpkg_extensions table extension name column value to specify implementation of SRS_ID triggers specified in <<extension_geometry_srsid_triggers>>.

[requirement]
A GeoPackage that implements srs_id triggers on feature table geometry columns SHALL contain a gpkg_extensions table that contains a row for each geometry column with extension_name “gpkg_srs_id_trigger”, table_name of the feature table with a geometry column, and column_name of the geometry column.

[requirement]
A GeoPackage SHALL include the SQL insert and update triggers specified in <<extension_geometry_srsid_triggers>> on every geometry column to enforce the srs_id values specified for those columns in the `gpkg_geometry_columns` table.

The <t> and <c> template parameters in the SRS_ID trigger definition SQL template in the table below are to be replaced with the names of the feature table and geometry column being inserted or updated

[source,sql]
----
CREATE TRIGGER fgsi_<t> _<c> BEFORE INSERT ON '<t>' FOR EACH ROW
BEGIN
  SELECT RAISE (ABORT, 'insert on <t>violates constraint: ST_SRID(<c>) does not match gpkg_geometry_columns.srs_id value')
  WHERE (SELECT srs_id FROM gpkg_geometry_columns
         WHERE Lower(table_name) = Lower('<t>')
	       AND   Lower(column_name) = Lower('<c>')
	       AND   ST_SRID(NEW.'<c>') <> srs_id) ;
END

CREATE TRIGGER fgsu_<t>_<c> BEFORE UPDATE OF '<c>' ON '<t>' FOR EACH ROW
BEGIN
  SELECT RAISE (ABORT, 'update of <c> on <t> violates constraint: ST_SRID(<c>) does not match gpkg_geometry_columns.srs_id value')
  WHERE (SELECT srs_id FROM gpkg_geometry_columns
         WHERE Lower(table_name) = Lower('<t>')
	       AND   Lower(column_name) = Lower('<c>')
	       AND   ST_SRID(NEW.'<c>') <> srs_id);
END
----

[float]
===== GeoPackage SQLite Configuration

None

[float]
===== GeoPackage SQLite Extension

Definition of SQL functions

[cols=",,,",options="header"]
|======
|SQL Function |Description |Use
|ST_SRID(geom. Geometry) : INTEGER |Returns the spatial reference system id of a Geometry |Check that geometry srid matches what's specified in `gpkg_geometry_columns.srid`
|======

[requirement]
The SQL function on geometries in this SQLite Extension SHALL operate correctly on extended geometry types specified by Annex J and/or Annex K when those extensions are also implemented.

[float]
==== Abstract Test Suite

[float]
===== Implementation

[cols="1,5a"]
|========================================
|*Test Case ID* |+/reg_ext/features/srs_id_triggers/implementation+
|*Test Purpose* |Verify that user feature data table srs_id triggers are implemented correctly.
|*Test Method* |
. SELECT table_name, column_name FROM gpkg_geometry_columns WHERE table_name IN (SELECT table_name FROM gpkg_contents WHERE data_type  == ‘features'))
. Not testable if result set is empty
. For each row table_name, column_name from step 1
.. SELECT sql FROM sqlite_master WHERE type = ‘trigger’ AND tbl_name = ‘fgsi_’ \|\| result_set_table_name \|\| ‘_’ \|\| result_set_column_name
.. Not testable if result set is empty
.. Fail if sql != result of populating the first trigger template in Annex N with <t> as result_set_table_name and <c> as result_set_column_name
.. SELECT sql FROM sqlite_master WHERE type = ‘trigger’ AND tbl_name = ‘fgsu_’ \|\| result_set_table_name \|\| ‘_’ \|\| result_set_column_name
.. Fail if sql != result of populating the second trigger template in Annex N with <t> as result_set_table_name and <c> as result_set_column_name
.. Log pass otherwise
. Pass if logged pass and no fails
|*Reference* |Annex F.5 Req 83
|*Test Type* |Capability
|========================================

[cols="1,5a"]
|========================================
|*Test Case ID* |+/reg_ext/features/srs_id_triggers/implementation/sql_functions+
|*Test Purpose* |Verify the correct implementation of sql functions used in srs_id triggers on feature table geometry columns.
|*Test Method* |
. Open Geometry Test Data Set GeoPackage with GeoPackage SQLite Extension
. For each Geometry Test Data Set <gtype_test> data table row for each geometry type in Annex G, for an assortment of srs_ids, for an assortment of coordinate values, without and with z and / or m values, in both big and little endian encodings:
.. SELECT ‘Fail’ FROM <gtype_test> WHERE ST_SRID(geom) != srs_id
. Pass if no ‘Fail’ selected from step 2
|*Reference* |Annex F.5 Req 84
|*Test Type* |Capability
|========================================

[float]
===== Extensions Name

[cols="1,5a"]
|========================================
|*Test Case ID* |+/reg_ext/features/srs_id_triggers/extension_name+
|*Test Purpose* |Verify that the “gpkg_srs_id_trigger” extension name is used to register srs_id triggers.
|*Test Method* |
. SELECT table_name, column_name FROM gpkg_geometry_columns WHERE table_name IN (SELECT table_name FROM gpkg_contents WHERE data_type  == ‘features'))
. Not testable if result set is empty
. For each row table_name, column_name from step 1
.. SELECT sql FROM sqlite_master WHERE type = ‘trigger’ AND tbl_name = ‘fgsi_’ \|\| result_set_table_name \|\| ‘_’ \|\| result_set_column_name
.. Not testable if result set is empty
.. /opt/extension_mechanism/extensions/data/table_def
.. Fail if failed
.. SELECT extension_name from gpkg_extensions WHERE table_name = result_set_table_name AND column_name = result_set_column_name
.. Pass if result is “gpkg_srs_id_trigger”
.. Fail otherwise
|*Reference* |Annex F.5 Req 85
|*Test Type* |Basic
|========================================

[float]
===== Extensions Row

[cols="1,5a"]
|========================================
|*Test Case ID* |+/reg_ext/features/srs_id_triggers/extension_row+
|*Test Purpose* |Verify that srs_id triggers are registered using the “gpkg_srs_id_trigger” extension name.
|*Test Method* |
 Do test /reg_ext/features/srs_id_triggers/extension_name
|*Reference* |Annex F.5 Req 86
|*Test Type* |Capability
|========================================

